### ISSUE TITLE
Broken DataGrid Styles

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#100]
The spacing between DataGrid columns seems to be broken:
![image](https://user-images.githubusercontent.com/17648453/154824723-17bc98da-e3e6-43f2-bc60-4a47488872f3.png)

DataGrid defined as follows:
```xml
<DataGrid Margin="6,6,6,6" MinHeight="200" AutoGenerateColumns="False" IsReadOnly="True" SelectionMode="Extended" GridLinesVisibility="Horizontal" Items="{Binding Downloads}">
  <DataGrid.Columns>
    <DataGridTextColumn Header="Filename" Binding="{Binding FullFilename}" MinWidth="240"/>
    
    <DataGridTextColumn Header="Video Link" Binding="{Binding VideoLink}" MinWidth="300"/>
    
    <DataGridTextColumn Header="Status" Binding="{Binding Status}" MinWidth="200"/>
    
    <DataGridTemplateColumn Header="Progress" MinWidth="200">
	    <DataGridTemplateColumn.CellTemplate>
		    <DataTemplate>
			    <Grid>
				    <ProgressBar HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Height="10" Minimum="0" Maximum="10" Value="{Binding Progress}"/>
			    </Grid>
		    </DataTemplate>
	    </DataGridTemplateColumn.CellTemplate>
    </DataGridTemplateColumn>
  </DataGrid.Columns>
</DataGrid>
```

**Comment by amwx** [comment]
I don't know much about the DataGrid (I don't use it other than in my sample app), so what is it supposed to look like - as it looks how I'd expect it.

**Comment by nlogozzo** [comment]
The content within the columns had some padding to them. It didn't look like this in versions of FluentAvalonia before 1.2.0
![image](https://user-images.githubusercontent.com/17648453/154875601-31ccdf73-68f5-4ea5-a864-a4a3c2ae51e8.png)

**Comment by amwx** [comment]
It was a change upstream. This was originally a margin hard coded in the C# code side, and was moved out in January: https://github.com/AvaloniaUI/Avalonia/commit/48bad22ebae29b8e399e31fc367687e38b6f19db

Adding this should fix this, which will need to be added to the DataGrid styles (feel free to PR if you'd like)
```Xaml
<!-- Resource -->
<Thickness x:Key="DataGridTextColumnCellTextBlockMargin">12 0</Thickness>

<Style Selector="DataGridCell > TextBlock#CellTextBlock">
    <Setter Property="Margin" Value="{DynamicResource DataGridTextColumnCellTextBlockMargin}" />
    <Setter Property="VerticalAlignment" Value="Center" />
</Style>
```
