### ISSUE TITLE
ProgressBar Error and Paused styles

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#105]
Hi,

WinUI's ProgressBar has the properties `ShowError` and `ShowPaused` in which the ProgressBar will stop in the middle and display a red and yellow color respectivly. Can we see these properties added to FluentAvalonia's ProgressBar?

**Comment by amwx** [comment]
Adding properties to ProgressBar would have to be done upstream - as that's a core Avalonia control. You could probably achieve a similar effect via attached properties, though. Not sure whether you could animate to the error or paused state this way.
