### ISSUE TITLE
ProgressRing Port

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#107]
Could we see a port of the new ProgressRing for this library?
https://docs.microsoft.com/en-us/windows/apps/design/controls/progress-controls
![image](https://user-images.githubusercontent.com/17648453/155735887-4ab43a69-7952-4f19-8fd4-f613e96046f9.png)

**Comment by robloo** [comment]
This should really be in Avalonia itself IMO. An attempt was made before but animation performance was a showstopper for some reason. Then discussion died out and the PR was closed.

**Comment by nlogozzo** [comment]
Well I mean for now we can port it as a control of this library using WinUI's source since main Avalonia doesn't seem interested. It'll probably get done faster here anyway 🤷🏻‍♂️

**Comment by robloo** [comment]
Upstream is definitely interested. It just isn't a solved problem yet. 

I just dont want controls like this to be an unnecessary burden to the maintainer of this repo. It's a lot of work already. Widely useful, non-controversial controls really should go in Avalonia upstream.

Agree this repo is faster though.

**Comment by robloo** [comment]
Here is Avalonia's attempt. It might be good to poke them in PR 6792 and see the final outcome. This doesn't use Lottie and is using Avalonia's native animation system. 

https://github.com/AvaloniaUI/Avalonia/pull/6003
https://github.com/AvaloniaUI/Avalonia/pull/6792

**Comment by nlogozzo** [comment]
See AvaloniaUI/Avalonia#7716

**Comment by ymg2006** [comment]
This has been done at [https://github.com/ymg2006/FluentAvalonia.ProgressRing](https://github.com/ymg2006/FluentAvalonia.ProgressRing)
