### ISSUE TITLE
navigation help

### ISSUE THREAD

**Issue by sabuto** [amwx/FluentAvalonia#112]
Hey so this might just be me being dumb but, currently the only way i see to navigate is with type of so for example

```csharp
new NavigationViewItem
            {
                Content = "Home",
                Tag = typeof(HomePageView),
                Icon = new SymbolIcon() { Symbol = Symbol.Home },
                Classes =
                {
                    "AppNav"
                }
            }
```

but say i want to use a DI container to resolve views how would i go about this?

**Comment by amwx** [comment]
I'll be honest I don't really know much about DI and how that works. But the NavigationView is ported from WinUI, so it might be worth a search to see if anything like that works in WinUI/UWP, and they should apply here as well.

**Comment by amwx** [comment]
#120 may also be of some use to any others looking to do something similar.
