### ISSUE TITLE
When CoreWindow is maximized and minimized and then restored, the window size will be reduced.

### ISSUE THREAD

**Issue by rmbadmin** [amwx/FluentAvalonia#115]
**Describe the bug**
When CoreWindow is maximized and minimized and then restored, the window size will be reduced.

**Desktop/Platform (please complete the following information):**
 - OS: Windows11
 - FluentAvalonia Version 1.3.0
 - Avalonia Version 0.10.13.0

**Comment by amwx** [comment]
Good catch. Win32 being Win32 again... Will take a look. Taking a quick guess, it probably is shrinking by 16 every time which is the WM_NCCALCSIZE modification and for some reason isn't being carried over into the window's size for some reason.

**Comment by alex6dj** [comment]
Just my grain of salt here. It shrink 16 px horizontally and 8 px vertically until the only thing left are minimize/restore/close buttons. At least in my personal case.
