### ISSUE TITLE
ToggleSwitch not aligned correctly to right

### ISSUE THREAD

**Issue by alex6dj** [amwx/FluentAvalonia#121]
**Describe the bug**
ToggleSwitch not get aligned to right correctly, even after set `OffContent=""` `OnContent=""`. Others controls get rendered correctly, but looks like ToggleSwitch have some right margin even when there is nothing to show there.
Maybe is because of:
```xml
<x:Double x:Key="ToggleSwitchThemeMinWidth">154</x:Double>
```

**Screenshots**
![Captura de pantalla (138)](https://user-images.githubusercontent.com/27690651/160257292-b214fe40-65a8-4177-9088-92866d67b20b.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version 1.3.2
 - Avalonia Version 0.10.13

**Additional context**

**Comment by amwx** [comment]
Duplicate of #36 

Correct, you can set the MinWidth to 0 and it will align correctly. The MinWidth comes from the WinUI design

**Comment by alex6dj** [comment]
Yes, your are right, I didn´t check to set MinWidth to 0, just tried with Width to 0.
