### ISSUE TITLE
Use Semantic Version

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#126]
**Is your feature request related to a problem? Please describe.**
Compatibility with Avalonia Core

**Describe the solution you'd like**
To avoid the problems of issue #125, FluentAvalonia should use the same versioning mode as Avalonia.

eg:
- FluentAvalonia 0.10.12.x is compatible with 0.10.12 of AvaloniaUI
- FluentAvalonia 0.10.13.x is compatible with 0.10.13 of AvaloniaUI

**Describe alternatives you've considered**

**Additional context**

**Comment by amwx** [comment]
I dislike semantic versioning, and prefer the old fashioned way, so I won't be changing that. The readme does specify the current Avalonia version targeted, which is almost always the latest stable release. Testing with Avalonia master is a "do at your own risk" thing given it has breaking changes and isn't supported. I plan to have separate beta-package/branch that is compatible with Avalonia master prepping for the 11.0 release so I can make changes gradually, but I'm waiting on at least 1 PR and the time to do it.

Additional note: I saw that you got my sample app running on Android. That's awesome! I don't have the mobile workloads installed so I can't do this on my own, but even it took a bit of work it's nice to see it does run there.

**Comment by workgroupengineering** [comment]
> I dislike semantic versioning, and prefer the old fashioned way, so I won't be changing that. The readme does specify the current Avalonia version targeted, which is almost always the latest stable release. Testing with Avalonia master is a "do at your own risk" thing given it has breaking changes and isn't supported. I plan to have separate beta-package/branch that is compatible with Avalonia master prepping for the 11.0 release so I can make changes gradually, but I'm waiting on at least 1 PR and the time to do it.

I understand your reasons, even at the beginning I thought like you. But when you have several dependent libraries, it depends on which versions are complicated, making it waste a lot of time to solve the problem.

With the semantic version you know on the fly that FluentAvalonia 0.11.0 is compatible with Avalonia 0.11.0.

> Additional note: I saw that you got my sample app running on Android. That's awesome! I don't have the mobile workloads installed so I can't do this on my own, but even it took a bit of work it's nice to see it does run there.

FluentAvalonia works quite well, I had to make a few small changes. I would like to do a PR but unfortunately I can't because I also had to make some changes to AvaloniaEdit.
