### ISSUE TITLE
ComboBox DisplayMemberPath, SelectedValue & SelectedValuePath

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [amwx/FluentAvalonia#13]
Very nice Controls!

ComboBox is ported from WinUI too right?
What happened to DisplayMemberPath, SelectedValue & SelectedValuePath ???
Do you have implemented something similar?

**Comment by amwx** [comment]
> ComboBox is ported from WinUI too right?

Not really. It's based on the Avalonia `ComboBox` implementation with an editable mode based on the `AutoCompleteBox` logic, which was really written as an experiment and behavior is still a little quirky. WinUI's `Combobox` is still closed source and this isn't something I'm interested in reverse engineering, especially on dealing with the properties below you're asking about...

> What happened to DisplayMemberPath, SelectedValue & SelectedValuePath ???
> Do you have implemented something similar?

`AutoCompleteBox` uses `ValueMemberBinding` property, which I've adapted, to replace `DisplayMemberPath`. Unlike WPF/UWP, you bind the property you want to that and the internal logic does the rest.
`<ui:ComboBox ValueMemberBinding="{Binding PropertyName}" />`

**Comment by robloo** [comment]
> Combobox is still closed source and this isn't something I'm interested in reverse engineering,

Would the plan be to port the full C++/WinRT ComboBox when WinUI3 fully open sources? I'm just trying to gauge scope here.

**Comment by amwx** [comment]
> 
> 
> > Combobox is still closed source and this isn't something I'm interested in reverse engineering,
> 
> Would the plan be to port the full C++/WinRT ComboBox when WinUI3 fully open sources? I'm just trying to gauge scope here.

That depends on if/how the Avalonia CB evolves between now and then, and how complex the WinUI CB is (i.e., if its another 2-4000+ line control that's more complicated than it needs to be, then no).
