### ISSUE TITLE
Allow specifying default theme as a fallback

### ISSUE THREAD

**Issue by PhantomGamers** [amwx/FluentAvalonia#147]
**Is your feature request related to a problem? Please describe.**
Currently when detecting the system theme fails, FluentAvaloniaTheme defaults to the LightModeString.

**Describe the solution you'd like**
Developers should be able to specify the default theme that is used when auto detection fails.

Also just a side note but wouldn't it be more appropriate for the *ModeString variables to be put into an Enum instead?

**Comment by amwx** [comment]
Detecting the system theme shouldn't fail and if it does then something else is wrong. The method I use now uses the WinRT APIs (`Windows.UI.ViewManagement.UISettings` for AccentColor & light/dark mode and `Windows.UI.ViewManagement.AccessibilitySettings` for high contrast mode). Both of these begin with Windows 10.0.10240 (1507) which means all Windows versions I support have these available.

**Comment by PhantomGamers** [comment]
It fails on Linux (and presumably OSX).

**Comment by amwx** [comment]
Resolving the system theme is only supported on Windows at the current time, which is why the property that controls that is `UseSystemThemeOnWindows`. For non-windows platforms, if you don't want to launch in the default light mode, change the `RequestedTheme` property when your app starts.
