### ISSUE TITLE
Unable to launch Linux app that depends on FluentAvalonia NuGet

### ISSUE THREAD

**Issue by PhantomGamers** [amwx/FluentAvalonia#160]
**Describe the bug**
So this is actually my bad, but as a result of #153 when a Linux app that depends on the FluentAvalonia NuGet is built and ran, it exits with the following exception:

> Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Controls.DataGrid, Version=0.10.15.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Avalonia.Controls.DataGrid, Version=0.10.15.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'
   at CompiledAvaloniaXaml.!AvaloniaResources.Populate:/Styling/BasicControls/DataGridStyles.axaml(IServiceProvider , Styles )
   at CompiledAvaloniaXaml.!AvaloniaResources.Build:/Styling/BasicControls/DataGridStyles.axaml(IServiceProvider )
   at CompiledAvaloniaXaml.!XamlLoader.TryLoad(String )

Oddly this doesn't happen for Windows builds, and it doesn't happen for Linux builds that depend on the FluentAvalonia project directly instead of the NuGet. I'm unsure about OSX as I do not have an OSX environment to test with.

Unless you have an idea of what the cause of this is, I think #153 should probably be reverted until a better solution is found, though this does kinda suck as it adds like 30MB to my app's output when Diagnostics is included. (This is assuming you can reproduce the behavior and there isn't just some other issue on my end causing this behavior)

**Desktop/Platform (please complete the following information):**
 - OS: Linux (via Windows WSL)
 - FluentAvalonia Version: 1.4.0
 - Avalonia Version 0.10.15

EDIT: It seems like just including a reference to Avalonia.Controls.DataGrid in the project that is referencing FluentAvalonia is enough to fix this, so maybe just noting this somewhere is enough and reverting the change isn't necessary, but of course you would expect simply referencing FluentAvalonia to also include everything that it requires.

**Comment by AigioL** [comment]
Diagnostics package should only be referenced during Debug, this should not be a problem, I have an application that used fork this repository to perform this change and it worked fine for a long time, so I don't think we should restore #153.

Maybe if you add a reference to the package ```Avalonia.Controls.DataGrid``` in your project and try generating it again, or delete the bin and obj folders and run ```msbuild -t:restore``` again, you might be able to fix it.

**Comment by PhantomGamers** [comment]
> Diagnostics package should only be referenced during Debug

Correct, but DataGrids is referenced in release as well.

> Maybe if you add a reference to the package Avalonia.Controls.DataGrid in your project

As I said in the post above, that does solve the issue, but this should not he necessary as you would expect all needed dependencies to be pulled in merely by referencing the FluentAvalonia nuget, and this is the case prior to #153 (e.g. in 1.3.5)

**Comment by amwx** [comment]
I just tested this in a blank project with my nuget and couldn't repro. I wonder if maybe the `Avalonia.Controls.DataGrid` dll was still an older version (0.10.14) for some reason and caused a conflict when it tried to load? That's the only thing I can think of
