### ISSUE TITLE
Different appearence for Mica between Debug and Publish

### ISSUE THREAD

**Issue by Dynesshely** [amwx/FluentAvalonia#165]
**Describe the bug**
When enabled Mica effect using the same way as the samples app done, it give different appearence between Debug mode and Publish mode.
It get the Desktop Backgounrd when in Debug mode.
But it can't get the Desktop Background when running published exe file.

**Screenshots**
When in debug mode:
![image](https://user-images.githubusercontent.com/50760269/172729560-aff25e73-dbe2-4fd3-bfa5-1f61f551baa2.png)
When in publish mode:
![image](https://user-images.githubusercontent.com/50760269/172729738-f3478901-6003-4c10-87a2-90f9c350cb52.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 21H2 22000.708 Windows 功能体验包 1000.22000.708.0
 - FluentAvalonia Version: latest => 1.4.0
 - Avalonia Version: latest => 0.10.5

**Additional context**
Or maybe it's winui's bug.

**Comment by Dynesshely** [comment]
By the way, the samples app also has this bug.

**Comment by amwx** [comment]
I'm unable to repro this, debug/release/publish builds all look the same.

However, Mica isn't really something I have control over though, it's built-in upstream in Avalonia. Can you repro this with a normal Avalonia window? If so, raising an issue there might be better.

**Comment by Dynesshely** [comment]
Oh, I thought Mica effect was provided by FluentAvalonia, omg, sorry for this, I did don't know this.
I will try it out.
Thanks.

**Comment by ControlNet** [comment]
I just found a way to solve it. Change the target runtime from `win-x64` to `win10-x64`.
