### ISSUE TITLE
Error CoreWindow Size

### ISSUE THREAD

**Issue by Dynesshely** [amwx/FluentAvalonia#179]
**Describe the bug**
I bind CoreWindow WidthProperty HeightProperty to ViewModel, value is 1280x720.
But finally window initialized, the actual size is 1264x712, why?

**Screenshots**
No not yet.

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 21H2 2022.‎06.‎01 Windows 功能体验包 1000.22000.795.0
 - FluentAvalonia Version 1.4.1
 - Avalonia Version 0.10.17

**Additional context**
No not yet.

**Comment by amwx** [comment]
Apologies for the delay in response - yes this is a known thing with CoreWindow. I believe some of the core logic in Avalonia's window class is conflicting with what I've put in CoreWindow which results in this discrepancy. It's not ideal, but as of right now I don't know how to fix it.

**Comment by Dynesshely** [comment]
tnx.
it's great helpful.

**Comment by Dynesshely** [comment]
Nice!

**Comment by Dynesshely** [comment]
I'm testing in the latest stable version of FluentAvalonia
I use the configuration file to record the last size of the form, and then restore this size the next time I open the form
But I had to add 30 to the height on startup and subtract 30 to store on shutdown
This will ensure that the next time you open the form, the correct size can be restored.

You can view my code at https://github.com/Crequency/KitX/blob/dev%3Dmain/KitX%20Dashboard/Views/MainWindow.axaml.cs#L68 and https://github.com/Crequency/KitX/blob/dev%3Dmain/KitX%20Dashboard/Views/MainWindow.axaml.cs#L231

I will try to not use CoreWindow. And change my code to do like Samples.

**Comment by amwx** [comment]
Don't use `ClientSize` to restore the properties, set `Width` and `Height` directly (it's fine though for saving). Given that `ClientSize` is a `protected set` property, I'm pretty sure it's not meant to be used for sizing directly. I can't repro your issue setting Width/Height directly:

```C#
Width = Program.Config.Windows.MainWindow.Window_Width;
Height = Program.Config.Windows.MainWindow.Window_Height;
```

**Comment by Dynesshely** [comment]
tnx, I will try it later

**Comment by Dynesshely** [comment]
![image](https://user-images.githubusercontent.com/50760269/197368947-2c9dfe7f-5b07-42e5-99e8-51817b2ec95a.png)

I changed to directly set Width and Height.
There are two window that one is CoreWindow and another is Window.
Both set to 1280x720, and as the image above, their Height has a difference about 30.
Their Top are aligned.
Is this because of CoreWindow?

**Comment by amwx** [comment]
When you made the change, did you test it without your OS checks for saving and loading the values? You code still has the "30" adjustment and that may be messing it up. 
That is:
```diff
private void SaveMetaData()
{
    Program.Config.Windows.MainWindow.Window_Left = Position.X;
    Program.Config.Windows.MainWindow.Window_Top = Position.Y;
-    if (OperatingSystem.IsWindows())
-    {
-        Program.Config.Windows.MainWindow.Window_Width = Width;
-        Program.Config.Windows.MainWindow.Window_Height = Height - 30;
-    }
-    else
-    {
        Program.Config.Windows.MainWindow.Window_Width = Width;
        Program.Config.Windows.MainWindow.Window_Height = Height;
-    }
    Program.Config.Windows.MainWindow.
        Tags["SelectedPage"] = SelectedPageName;
}
```

```diff
public MainWindow()
{
     // ctor code

 try
{
-    if (OperatingSystem.IsWindows())
-    {
-        Width = Program.Config.Windows.MainWindow.Window_Width;
-        Height = Program.Config.Windows.MainWindow.Window_Height + 30;
-    }
-    else
-    {
        Width = Program.Config.Windows.MainWindow.Window_Width;
        Height = Program.Config.Windows.MainWindow.Window_Height;
-    }
}
catch (Exception e)
{
    Log.Error(e, e.Message);
    ClientSize = new(800, 600);
}
```

> Is this because of CoreWindow?

I can't repro this issue in a simple test case (just writing ClientSize to a file on exit, and reading that file back on restart) so I don't think so. Have you double checked that the values of the window's size are actually what's being written (set a breakpoint and look at what ClientSize is), verified it in the settings file (is it the same from inspecting at the breakpoint), and are correct in the ctor when you reload it (are they all the same).

**Comment by Dynesshely** [comment]
> When you made the change, did you test it without your OS checks for saving and loading the values? You code still has the "30" adjustment and that may be messing it up.

I tested without OS check and 30 heights adjustment (just like your example), which wasn't committed.

> I can't repro this issue in a simple test case (just writing ClientSize to a file on exit, and reading that file back on restart) so I don't think so. Have you double checked that the values of the window's size are actually what's being written (set a breakpoint and look at what ClientSize is), verified it in the settings file (is it the same from inspecting at the breakpoint), and are correct in the ctor when you reload it (are they all the same).

I will do further testing. Tnx.

Sorry for late response, monday to saturday I need to stay at school.
