### ISSUE TITLE
1.4.2 references Avalonia.Diagnostics

### ISSUE THREAD

**Issue by satial-interfaces** [amwx/FluentAvalonia#187]
Version 1.4.2 references Avalonia.Diagnostics, whereas version 1.4.1 did not. Meaning Microsoft.CodeAnalysis.* is back and added unnecessary size to the package.

Checked with a simple Avalonia-app (version 0.10.18) and nuget.org (Dependencies).

**Comment by amwx** [comment]
Not sure what caused that. I haven't touched the conditional for Avalonia.Diagnostics which keeps it to debug builds only. I'll see what I can do

**Comment by satial-interfaces** [comment]
Thx

**Comment by amwx** [comment]
I just pushed out package v1.4.3. Only thing it does is attempt to not ref Avalonia.Diagnostics. I checked the bin/Release dirs and I don't see any of the offending dlls there so hopefully this fixes it. Still not sure why it happened but let me know if its still a problem.

**Comment by satial-interfaces** [comment]
Yes, it's fixed. It doesn't reference the assembly anymore. Thx!
