### ISSUE TITLE
Support Null Owner

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#189]
For TaskMessageBox, could you support setting Null as the owner? It would then call Show instead of ShowDialog.

This could allow displaying a message before the application is started or after it is closed.

**Comment by amwx** [comment]
Non-modal windows (`.Show()`) don't work with the dialog result parameter which would require reworking the logic of the window to deal with whether or not the `XamlRoot` property is set, therefore TaskDialog was designed to be a modal window. If you want a dialog experience before/after app run either use a hidden window to trick the dialog, show the main window but don't load content until after the dialog, or implement your own windowed experience to handle it.
