### ISSUE TITLE
Change of metrics of `AppBarButton`

### ISSUE THREAD

**Issue by davidxuang** [amwx/FluentAvalonia#198]
**Describe the bug**
In the lastest preview version, `AppBarButton` (with `TransparentButton` theme) will have a `BorderThickness` of 1, which makes it a little bigger than original `FluentAvalonia.UI.Controls.Button` with `AppBarButton`. Is `AppBarButton` not fully implemented, or being deprecated, or having a breaking change?

**Screenshots**
Change of metrics causes the inner content being clipped.
![图片](https://user-images.githubusercontent.com/24728204/190714047-e038e4ad-0136-477c-8a21-4d2e159b7cb1.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 Beta
 - FluentAvalonia Version latest preview
 - Avalonia Version latest preview

**Additional context**

**Comment by amwx** [comment]
Yes it does seem I inadvertently changed the border thickness. Feel free to submit a PR to restore it to 0 as was in 1.x
https://github.com/amwx/FluentAvalonia/blob/3dadc4d1535249e5f99cdfce9aecd036da6a2629/FluentAvalonia/Styling/ControlThemes/BasicControls/ButtonStyles.axaml#L102
