### ISSUE TITLE
[Feature Request] CommandBar

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#20]
Would you be able to port the [CommandBar](https://docs.microsoft.com/en-us/windows/apps/design/controls/command-bar) from WinUI? And maybe the [TabbedCommandBar](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabbedcommandbar)?

**Comment by amwx** [comment]
Good news! The `CommandBar` is coming in the v1.1 update (#18) as it was a prerequisite for the `CommandBarFlyout`. It's not a 1:1 port (still closed source), but it does function in terms of primary/secondary commands, dynamic overflow - basically like a toolbar. Animations, and other super specific functionality that MS black magic-d into it won't be supported (either Avalonia doesn't support it, or I can't figure out how MS did it)

As for the `TabbedCommandBar`, that's interesting - I hadn't seen that in the community toolkit yet. I'll look into it, but it obviously won't be included in v1.1 release

**Comment by nlogozzo** [comment]
No worries. Thanks for the great work. Can't wait to try `CommandBar` in the next release...any idea when it'll be merged? And also yeah the `TabbedCommandBar` is a fancy way to create a ribbon interface with WinUI

**Comment by amwx** [comment]
> 
> 
> No worries. Thanks for the great work. Can't wait to try `CommandBar` in the next release...any idea when it'll be merged? And also yeah the `TabbedCommandBar` is a fancy way to create a ribbon interface with WinUI

Finishing up some small things and making sure there's no outstanding obvious bugs with all the new controls, so unless something major comes up, next couple days.

**Comment by nlogozzo** [comment]
Cool... super excited :) if you wanna create a dev release on nuget and I can help test I'd be more than happy to. Otherwise can't wait to try the release!
