### ISSUE TITLE
Avalonia WASM build fails with Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.	Test.Web	C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.10\Sdk\WasmApp.Native.targets

### ISSUE THREAD

**Issue by saibot75** [amwx/FluentAvalonia#218]
**Describe the bug**
WASM build (Test.Web in my case) fails with:
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.10\Sdk\WasmApp.Native.targets(244,5): error : Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.
Done building project "Test.Web.csproj" -- FAILED.

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10 wasm
 - FluentAvalonia Version 2.0.0-preview2
 - Avalonia Version 11.0.0-preview2

**Additional context**
Create the default Avalonia MVVM together with WASM project (11.0.0-preview2). 
Add FluentAvalonia 2.0.0-preview2.
Build .Web project -> FAILED

**Comment by amwx** [comment]
Should no longer be an issue with preview3. Avalonia.Desktop reference was removed from main package

**Comment by michalss** [comment]
not fixed. Still Happening :(

`2>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0\Sdk\WasmApp.Native.targets(292,5): error : Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.
`
