### ISSUE TITLE
Use XmlnsDefinitionAttribute to map XML namespace to CRL namespace

### ISSUE THREAD

**Issue by thexamlguy** [amwx/FluentAvalonia#228]
In doing so, this will remove all of the ugly namespace prefixes found all over the XAML, i.e.

From this:
```
<UserControl
    x:Class="Builder.ProjectView"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:fluent="using:FluentAvalonia.UI.Controls">
    <StackPanel>
        <fluent:Frame />
        <fluent:FontIcon />
        <fluent:NavigationView>
            <fluent:NavigationView.MenuItems>
                <fluent:NavigationViewItem />
			<fluent:NavigationViewItem />
	        </fluent:NavigationView.MenuItems>
        </fluent:NavigationView>
    </StackPanel>
</UserControl>
```

to this
```
<UserControl
    x:Class="Builder.ProjectView"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <StackPanel>
        <Frame />
        <FontIcon />
        <NavigationView>
            <NavigationView.MenuItems>
                <NavigationViewItem />
			<NavigationViewItem />
		</NavigationView.MenuItems>
        </NavigationView>
    </StackPanel>
</UserControl>
```

This can be done by adding a few lines to the Assembly.cs file in the FluentAvalonia.UI.Controls project.
```
using Avalonia.Metadata;
[assembly: XmlnsDefinition("https://github.com/avaloniaui", "FluentAvalonia.UI.Controls")]

```

**Comment by amwx** [comment]
I *really* don't like when 3rd parties do this. 
1- It causes issues with the designer and I don't wanna have to triage issues relating to "why isn't this working"
2- It makes it seem the 3rd party controls are part of the main library - which they're not. This violates Xml specs, as nodes in different namespaces need their xmlns prefix
3- It could cause type name clashes. Until recently, I had a couple controls that had the same name as upstream. I've now prefixed them with 'FA' to distinguish, but this could cause other issues

I get this makes the Xaml a little cleaner and removes the need to add the xmlns stuff (which can be annoying for every xaml file), but IMO this is a bad practice.
