### ISSUE TITLE
[Bug] Unable to change InfoBar Severity

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#23]
I'm able to create a regular InfoBar no issues `<ui:InfoBar Name="InfoBar" HorizontalAlignment="Stretch" VerticalAlignment="Bottom" IsOpen="True" Title="Test" Message="Test" IsClosable="False"/>` and it defaults to using the Information severity. When I go to change the severity, for example, `Severity="Warning"` I get a NullReferenceException (this also happens if I try "Error" or anything else).
![image](https://user-images.githubusercontent.com/17648453/126514169-9c4f91d8-9b6a-4236-ad72-c2f99ef9a70b.png)

**Comment by amwx** [comment]
Fixed in v1.1, now merged
