### ISSUE TITLE
ContentDialog is handling the Cancel property before checking the deferral

### ISSUE THREAD

**Issue by TheXamlGuy** [amwx/FluentAvalonia#239]
The correct behaviour is to check the value of the Cancel property after checking the deferral. This is evidenced in the UWP\WinUI's ContentDialog control.

This is a snippet from UWP.
```
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            ContentDialog d = new ContentDialog();
            d.PrimaryButtonText = "Test";
            d.PrimaryButtonClick += D_PrimaryButtonClick;

            await d.ShowAsync();
        }

        private async void D_PrimaryButtonClick(ContentDialog sender, ContentDialogButtonClickEventArgs args)
        {
            var d = args.GetDeferral();

            await Task.Delay(TimeSpan.FromSeconds(5));

            // Not happy anyway, so we'll not close.
            args.Cancel = true;

            d.Complete();
        }
```

Offending lines:
https://github.com/amwx/FluentAvalonia/blob/123d8af4da08749aa89ea4f01f4c2b61b08842eb/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L268

https://github.com/amwx/FluentAvalonia/blob/123d8af4da08749aa89ea4f01f4c2b61b08842eb/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L468

https://github.com/amwx/FluentAvalonia/blob/123d8af4da08749aa89ea4f01f4c2b61b08842eb/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L491

https://github.com/amwx/FluentAvalonia/blob/123d8af4da08749aa89ea4f01f4c2b61b08842eb/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L514

**Comment by TheXamlGuy** [comment]
Ok. After some deeper investigation the offending codes lives in the ContentDialogButtonClickDeferral class. It just doesn't acknowledge the Cancel value before proceeding with decision to close or keep the dialog open depending on the value of the Cancel property.

**Comment by amwx** [comment]
Yes, ContentDialog needs a little refactoring. This briefly crossed my mind when I did the TeachingTip port where a deferral is used there too, so thanks for reminding me - added to the list
