### ISSUE TITLE
[Bug] Unable to create custom ContentDialog

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#24]
Hi, I'm trying to create a custom Dialog that extends a ContentDialog. My xaml and c# are below:
```xml
<ui:ContentDialog x:Class="NickvisionApp.Views.WelcomeDialog"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:ui="using:FluentAvalonia.UI.Controls"
             mc:Ignorable="d" d:DesignWidth="600" d:DesignHeight="400"
             Title="Welcome" PrimaryButtonText="Finish" CloseButtonText="Close" DefaultButton="Close"
             Width="600" Height="400">
    <StackPanel>
        
    </StackPanel>
</ui:ContentDialog>
```
```csharp
using Avalonia.Markup.Xaml;
using FluentAvalonia.UI.Controls;

namespace NickvisionApp.Views
{
    public class WelcomeDialog : ContentDialog
    {
        public WelcomeDialog()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```
However, I'm getting this error:
![image](https://user-images.githubusercontent.com/17648453/126523031-614f5289-462b-4857-9787-09c6b213eeee.png)

**Comment by amwx** [comment]
This is an interesting one. I was able to repro this. For some reason it seems the template isn't applying resulting in the null ref - not sure why though, but will look into it

**Comment by nlogozzo** [comment]
Yeah it said something about the `_primaryButton` being null when it tried to access the `IsVisible` property inside the switch statement in the `SetupDialog` method.
Don't know if that helps, that's what Rider debugger said when it de compiled the source @amwx

**Comment by nlogozzo** [comment]
Any updated? @amwx 
Also do you have a discord or something where we can better communicate and I could maybe help debug and fix issues?

**Comment by amwx** [comment]
Implement `IStyleable` and set the `StyleKey` to `ContentDialog`, that should fix it. 
````
public partial class WelcomeDialog : ContentDialog, IStyleable
{
	Type IStyleable.StyleKey => typeof(ContentDialog);
````
The `StyleKey` typically defaults to the `Type` of custom controls, so was looking for a Selector matching `WelcomeDialog`, so we just need to redirect it back to `ContentDialog` to give it the template it needs.

On another note, you probably don't want to set a Width/Height to the dialog, as that will constrain the "smoke screen" behind the dialog too, and it will all look weird. But if you really want to enforce that size, you'll have to do it through Styles to target the actual dialog container:
````
<!-- Override this resource which defaults to 548 -->
<ui:ContentDialog.Resources>
	<x:Double x:Key="ContentDialogMaxWidth">600</x:Double>
</ui:ContentDialog.Resources>

<ui:ContentDialog.Styles>
	<Style Selector="ui|ContentDialog /template/ Grid#DialogSpace">
		<Setter Property="Width" Value="600"/>
		<Setter Property="Height" Value="400" />
	</Style>
</ui:ContentDialog.Styles>
````

**Comment by nlogozzo** [comment]
That worked! Thanks @amwx 
Just a quick question, how do you close the `ContentDialog` from code? For example, I have a progress dialog:
```csharp
using System;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Styling;
using FluentAvalonia.UI.Controls;

namespace NickvisionApp.Views
{
    public class ProgressDialog : ContentDialog, IStyleable
    {
        private Func<Task> _action;
        
        Type IStyleable.StyleKey => typeof(ContentDialog);

        public ProgressDialog()
        {
            AvaloniaXamlLoader.Load(this);
        }
        
        public ProgressDialog(string description, Func<Task> action)
        {
            AvaloniaXamlLoader.Load(this);
            _action = action;
            this.FindControl<TextBlock>("LblDescription").Text = description;
        }

        private async void Loaded(ContentDialog sender, object e)
        {
            await _action();
            OnCloseButtonClick(null);
        }
    }
}
```
I want it to close after the `await _actioon();` line has completed. I tried using `OnCloseButtonClick` because it seemed like the closest thing, but it doesn't work. With UWP/WinUI, I was able to use the `Hide` method which was part of the `ContentDialog` but it doesn't seem to exist in this library. Any ideas?

**Comment by amwx** [comment]
Yea, I apparently forgot to include the `Hide` method. I have other things I need to do this week, so I don't know when I'll get to making some of these fixes, but this is on the list to fix for the next minor release.

As a temporary workaround, you might be able to do, though I haven't tested to see if it works:
1- if you don't mind a little reflection, you can try to invoke the private `HideCore` method of `ContentDialog` 
2- Or you may be able to force it closed by raising the `KeyUp` event on purpose with the escape key
Something like (wrote this from memory, may not be correct):
`RaiseEvent(new KeyEventArgs() { Key = Key.Escape, RoutedEvent=KeyUpEvent })`
as the escape key cancels the dialog

**Comment by nlogozzo** [comment]
`RaiseEvent(new KeyEventArgs() { Key = Key.Escape, RoutedEvent = KeyUpEvent });` worked! Thanks so much for all your help!
