### ISSUE TITLE
Wasm Error with Preview4

### ISSUE THREAD

**Issue by michalss** [amwx/FluentAvalonia#247]
When you create a new Project just add  FluentAvaloniaUI" Version="2.0.0-preview4" will fail to run with WASM.

```
2>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0\Sdk\WasmApp.Native.targets(292,5): error : Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.
```

**Comment by amwx** [comment]
First, thanks for reporting.
Two questions: 
- The error text you posted says .net 7, is this the new WASM backend that's .net7 only, or is this the old one and you're just on .net7?
- Can you post just a minimal repro of this? I know you say just add the package, but I'm not very familiar with WASM (especially if this is the new .net7 only one) and my last attempt with it was not a very nice experience .

**Comment by michalss** [comment]
i will upload a example in 5 mins

**Comment by michalss** [comment]
[TestAvaloniaFluent.zip](https://github.com/amwx/FluentAvalonia/files/10094851/TestAvaloniaFluent.zip)

This i pure template and i just added FluentAvaloniaUI.

**Comment by amwx** [comment]
Don't reference `FluentAvalonia.UI.Windowing` package in the main project. That is a desktop only package and should only be used in the desktop project. Removing that reference I got the project to build and run: <br />
![image](https://user-images.githubusercontent.com/40413319/204115831-9b822409-4152-405d-8cec-e2dfdce6f4e2.png)

**Comment by michalss** [comment]
well i forget to remove it. But still wasm wont start with for example navigationview.. Did you even try all components ?
