### ISSUE TITLE
CommandBar Improvements

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#25]
I'm testing out the current V1.1.0 release and I love it, really amazing work!
However, I just had some suggestions/improvements for the `CommandBar`. Here is my xaml for reference:
```xml
<ui:CommandBar HorizontalAlignment="Stretch" VerticalAlignment="Top" DefaultLabelPosition="Right">
    <ui:CommandBar.PrimaryCommands>
      <ui:CommandBarButton Label="Add" Icon="Add"/>
    </ui:CommandBar.PrimaryCommands>
    
    <ui:CommandBar.SecondaryCommands>
      <ui:CommandBarButton Label="Open" Icon="Open"/>
    </ui:CommandBar.SecondaryCommands>
</ui:CommandBar>
```

The first thing is when the label is displayed to the right, the text is off-centered of the icon, as you can see below:
![image](https://user-images.githubusercontent.com/17648453/126561880-bd3bba64-cd77-4075-825c-11ba0e8857f2.png)

Another request, is to have the `CommandBar` use the same background (or at least a darker color to show it is a bar of some sort) as the `NavigationView` and `MenuBar`:
![image](https://user-images.githubusercontent.com/17648453/126562033-ae440a51-5960-4fa4-807a-a8e838553d3e.png)
Regarding this, ^, is there a `DynamicResource` brush or something I can set for the background that would match the same brush used as the background of the `NavigationView` and `MenuBar`?

**Comment by amwx** [comment]
> The first thing is when the label is displayed to the right, the text is off-centered of the icon, as you can see below:

Sometimes sizes/margins/paddings don't port very nicely. I had to make the Viewbox holding the icon in the template bigger so it better matches WinUI (it's 16px in WinUI, I bumped to 20px, as it was too small, but I don't know why) adjusting that makes the margins wrong and pushes the icon too far down. This is a simple fix. The other thing, which I don't think is the primary issue here, and is where taking WinUI cross platform has issues, is the margins applied to TextBlocks in many WinUI templates are based on the Segoe UI font, which doesn't necessarily exist outside of Windows, and other fonts don't always align the same. So it may not be 100% possible to perfectly align 

> Regarding this, ^, is there a `DynamicResource` brush or something I can set for the background that would match the same brush used as the background of the `NavigationView` and `MenuBar`?

The `NavigationView` pane and `MenuBar` are transparent by default (that's just what MS decided) so the darker color is the default Window/page color, which I believe is `SolidBackgroundFillColorBaseBrush`

All colors & brushes are here for v2 styles (the resource keys are the same for dark theme):
https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/Styling/StylesV2/LightResources.axaml

**Comment by nlogozzo** [comment]
> The other thing, which I don't think is the primary issue here, and is where taking WinUI cross platform has issues, is the margins applied to TextBlocks in many WinUI templates are based on the Segoe UI font, which doesn't necessarily exist outside of Windows, and other fonts don't always align the same. So it may not be 100% possible to perfectly align. 

Would we be able to add SegoeUI Font file to the framework or something and use it in the styles?

> The `NavigationView` pane and `MenuBar` are transparent by default (that's just what MS decided) so the darker color is the default Window/page color, which I believe is `SolidBackgroundFillColorBaseBrush`

That was it! Thanks :)

**Comment by nlogozzo** [comment]
@amwx I changed the background to match however I'm experiencing another issue:
![image](https://user-images.githubusercontent.com/17648453/126586001-0cfc12a4-d6c2-4705-aa97-039d5bcf2573.png)
![image](https://user-images.githubusercontent.com/17648453/126586078-712b502d-8a80-4a14-bc28-657efe3350ca.png)
Notice how when I go to click `...` to display the secondary commands, the background becomes transparent on the command bar. When I close the secondary commands, it goes back to what i set it to.

**Comment by amwx** [comment]
When the `CommandBar` `IsOpen=true`, the background is changed (it also adds a border), which was added as part of the v2 Fluent styles, e.g., in WinUI XamlControlsGallery:
![image](https://user-images.githubusercontent.com/40413319/126589194-0f487965-1178-4a85-aed5-b853341c2503.png)

To not do this, you'll have to override this Style Selector to set the background to whatever (replace `CommandBarBackgroundOpen` with the resource you want.
https://github.com/amwx/FluentAvalonia/blob/7e508a34f1cf5f32799143daeba455763b2a671c/FluentAvalonia/Styling/Controls/CommandBar/CommandBar.axaml#L271-L275

**Comment by nlogozzo** [comment]
That worked! Thanks for all the help again :)
