### ISSUE TITLE
TreeDataGrid support planned?

### ISSUE THREAD

**Issue by iOutSide** [amwx/FluentAvalonia#258]
Hi. Do you plan to add styles/templates for TreeDataGrid? As for now seems you do not support this control,
<sty:FluentAvaloniaTheme />
<StyleInclude Source="avares://FluentAvalonia.UI.Windowing/Styles/FAWindowingStyles.axaml" />

is not enouth to work with TreeDataGrid

**Comment by amwx** [comment]
At this time, I have no plans to add the styles for TreeDataGrid as it's A) outside the main Avalonia library, and B) considered a "premium" control with support only for Avalonia's paying customers.

However, it shouldn't be too hard to add the styles yourself. They should mostly work, you'll just have to update/change some of the brush resources to the Fluent v2 naming.
