### ISSUE TITLE
TextBox Header

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#26]
Hello again,
Is there a way we can add a header to a textbox control similarly to WinUI. There is already the watermark feature but no header. Maybe like a textbox helper where we could do:
```xml
<TextBox ... ui:TextBoxHelper.Header="Name"/>
```

**Comment by amwx** [comment]
Although I do agree it'd be nice to have this, I think this is a feature request probably better suited for the core Avalonia repo. IIRC, TextBox is supposed to get a refresh as part of the RichText stuff coming soon, so it might be possible to get it added there. I'd like to keep duplicate controls to a minimum to reduce confusion (already have dups of Button, MenuFlyout and technically ComboBox), especially if the changes are subtle. Also would rather not rely on AttachedProperties/helpers as I don't think that's a great widespread solution
