### ISSUE TITLE
Incorrect Collapsed ScrollBar Thumb CornerRadius

### ISSUE THREAD

**Issue by robloo** [amwx/FluentAvalonia#263]
**Describe the bug**

This one is hard to see. However, when the ScrollBar Thumb collapses to its "mini" state (sorry, forgot the name) the corner radius is still using the large state's value. This results in the ends of the scroll bar thumb becoming stretched and "pointed" visually.

This may not be an actual issue and simply could be a rendering difference between WinUI and Avalonia.

**Screenshots**

Large state -- this is correct

![image](https://user-images.githubusercontent.com/17993847/209735337-4b642588-38e1-45fe-a7d3-52924cde47b0.png)

Collapsed "mini" state -- this looks incorrect compared to Windows themes

![image](https://user-images.githubusercontent.com/17993847/209735297-f3f0e891-32fa-4b8c-a4cf-8c71dc917ad6.png)

**Desktop/Platform (please complete the following information):**
 - OS: [e.g. Windows (11/10), linux (distro), osx, wasm, etc]
 - FluentAvalonia Version [e.g. 1.0.0, or latest]
 - Avalonia Version [e.g. 0.10.10]

**Additional context**

I will fix this once direction is agreed.

**Comment by amwx** [comment]
Already went ahead and fixed this in preview5 branch. I had some CornerRadius values wrong. The ScrollBar templates are complex and differ significantly from WinUI so I've kinda just hacked it all together until it looks about right. But thanks for catching this

Collapsed state in preview 5
![image](https://user-images.githubusercontent.com/40413319/209872171-2500bc92-5c6e-4cf1-88f9-12892f9f0bf6.png)

**Comment by robloo** [comment]
Great! Thanks for looking at this so quickly.
