### ISSUE TITLE
Scroll Repeat Button appears in menu when desktop scaling is greater than 100%

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#27]
If you open a menu while you've set your desktop scaling to 125% or more, a button appears at the bottom indicating there is more to scroll. But there is no more menu items that are not visible.
![Screenshot (24)](https://user-images.githubusercontent.com/5307160/126850109-63742dac-a071-45fc-9d6d-6c1750a4f7cc.png)

This does not happen with Avalonia Fluent theme

**Comment by amwx** [comment]
Thanks for the report. Had a quick look myself and could repro, and seems it does only happen with the new v2 Styles so I suspect there's a margin or padding doing something weird here in the new theme-I'll have a bigger look to figure out why

**Comment by amwx** [comment]
Fixed in new update, well technically. WinUI new Fluent theme uses a normal `ScrollViewer` in menus so the special `menuScroller` class on the `ScrollViewer` in MenuBar items was removed to match, which also fixed the problem.
