### ISSUE TITLE
Add x:Uid to localize string resources from .resw files

### ISSUE THREAD

**Issue by onionware-github** [amwx/FluentAvalonia#275]
In UWP/WinUI Apps, you can use x:Uid to get the right string resources for the current language. These are stored as .resw files in a folder called "Strings" in the project root. Is it possible to add this functionality to (Fluent-)Avalonia? 

MyProject
- Strings
-     de-de
         Resources.resw
         AppSettings.resw
-     en-us
          Resources.resw
          AppSettings.resw
<Textblock x:Uid="/AppSettings/convertSettingsTitle"/>

And if not, how can I localize these string resources and use it in the UI? Create a Dictionary of keys and values and bind the keys like this?
<Textblock Text="{Binding appSettingsResources["convertSettingsTitle]}"/>

**Comment by amwx** [comment]
This is outside the scope of this project, but there have been many discussions on localization support within Avalonia (in their repo or the gitter/telegram chat). x:Uid isn't supported currently. I think what most are doing is using a custom markup extension. [see this discussion as an example](https://github.com/AvaloniaUI/Avalonia/discussions/7131)
