### ISSUE TITLE
Dialogs derived from ContentDialog don't inherit styles

### ISSUE THREAD

**Issue by taj-ny** [amwx/FluentAvalonia#276]
**Describe the bug**
Custom dialogs derived from the ContentDialog class don't inherit styles. The dialog is present in the visual tree after showing, however it's not visible. No exceptions are thrown. This problem doesn't exist on WinUI.

**Desktop/Platform (please complete the following information):**
 - OS: Arch Linux, 6.1.7-zen1-1-zen, KDE Plasma 5.26.5
 - FluentAvalonia Version: 2.0.0-preview4 (also affects preview5 at the time of creation of this issue)
 - Avalonia Version: 11.0.0-preview4

**Additional context**
This can be fixed manually by adding the following code to the derived dialog:
```xaml
<ui:ContentDialog.Resources>
    <ResourceDictionary>
        <ControlTheme x:Key="{x:Type local:CustomContentDialog}"
                      TargetType="local:CustomContentDialog"
                      BasedOn="{StaticResource {x:Type ui:ContentDialog}}" />
    </ResourceDictionary>
</ui:ContentDialog.Resources>
```

An example is available here: https://github.com/taj-ny/FluentAvaloniaContentDialogBug.

**Comment by TheXamlGuy** [comment]
I don't know if the issue with deriving from a custom third party control is intentional... however I do this code behind of the control to get around the above issue.

```
public partial class SettingsView : ContentDialog, IStyleable
{
    public SettingsView()
    {
        InitializeComponent();
    }

    Type IStyleable.StyleKey => typeof(ContentDialog);
}
```

**Comment by amwx** [comment]
Yes, just to expand: the StyleKey for controls is basically defined as `Type IStyleable.StyleKey => typeof(this)`, so the style key is always the type of control you're working on. So for inheriting purposes, you have to reset that key back to the parent type you want.
