### ISSUE TITLE
DataGrid failed to pop up menu

### ISSUE THREAD

**Issue by wj8400684** [amwx/FluentAvalonia#279]
![image](https://user-images.githubusercontent.com/39239954/215334768-fc9c35f1-0949-45e0-b360-56e37428395f.png)、

![image](https://user-images.githubusercontent.com/39239954/215334848-244664cd-6a2c-4ffb-8bff-cce5eff21bf4.png)
Right click can't pop up the menu. Is it the wrong way I use it?

**Comment by amwx** [comment]
Use `ContextFlyout` instead. I've omitted the styles for `ContextMenu` as flyouts have a richer API. This has been advertised before, but I've made a note to make sure add that to the documentation (which will get more attention after preview5 *finally* releases)

**Comment by wj8400684** [comment]
When will preview5 be released?
