### ISSUE TITLE
Starting app in Fullscreen mode doesn't work

### ISSUE THREAD

**Issue by jack775544** [amwx/FluentAvalonia#282]
**Describe the bug**

I am creating an application using the Windowing package that I want to be full screen when it is opened. However when I try to do this, the window will not have any decorations and cannot be dragged as expected. But the window will not expand to take the entire screen space, instead it will be the size as if the WindowState is set to Normal.

I can replicate this issue in my own application, a brand new application made from the avalonia.app template and then had FluentAvalonia installed as well as by modifying the sample application in this repo as well. In all these cases I have added `WindowState="FullScreen"` to MainWindow.axaml.

One mitigation that I have found was to delay making the application full screen until a bit after the application starts. Leaving the WindowState as Normal and then adding this into the window constructor does work correctly.

```cs
Task.Delay(2000).ContinueWith(_ =>
{
    Dispatcher.UIThread.Post(() =>
    {
        WindowState = WindowState.FullScreen;
    });
});
```

Also I did some very limited testing on Ubuntu via WSL 2 and found that the application would start in Fullscreen with no other changes so it seems like a Windows only bug.

**Desktop/Platform (please complete the following information):**

 - OS: Windows 11 (10.0.22621.1105) & Windows 10 (10.0.19045.2486)
 - FluentAvalonia Version: 2.0.0-preview4
 - Avalonia Version: 11.0.0-preview4

**Additional context**

I have tested this out on 2 different machines, one with x1.25 scaling and the other with x1 scaling and the issue still occurs.

**Comment by amwx** [comment]
Issue should be fixed in preview5

**Comment by jack775544** [comment]
Great to hear. Thanks for the quick turnaround.
