### ISSUE TITLE
TaskDialog window size broken

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#296]
I'm updating MvvmDialogs for Avalonia11-preview5; having some issues with Fluent TaskDialog.

All task dialogs now show like this. Any idea what could be going wrong?

![Screenshot_10](https://user-images.githubusercontent.com/8528033/218154608-7aadbf49-c651-474e-ba54-2581d8aa02b9.png)

Showing a TaskDialog is done here
https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/blob/master/src/MvvmDialogs.Avalonia.Fluent/FluentApi.cs#L24

**Comment by amwx** [comment]
No clue, and I can't repro that. 
What OS? Is the task dialog displaying windowed or hosted (overlay). Try peeking around with DevTools, that may help shed some light.

**Comment by mysteryx93** [comment]
I'm on Linux, windowed mode.

I'd try on Windows but am having some issue running Avalonia on it ATM.

**Comment by mysteryx93** [comment]
Found the problem. App.axaml needs

    <StyleInclude Source="avares://FluentAvalonia.UI.Windowing/Styles/FAWindowingStyles.axaml" />
