### ISSUE TITLE
Dark background when showing multiple ContentDialogs

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#304]
In the rare case where multiple ContentDialogs would get shown simultaneously on top of each other (let's say a background task runs and 3 different prompts show up while it's working), then the window background gets darker 3 times.

It's really not a big deal and happens in edge cases, but still, is there a way to prevent that from happening? If the background is already grayed out, it shouldn't gray it even more.

**Comment by amwx** [comment]
You should have some mechanism that prevents more than one dialog from showing at one time. Technically, WinUI enforces this as you can only have 1 ContentDialog active per thread at one time. Additional dialogs are queued and shown as the previous one closes. I originally tried to do something like this, but it made the code complex and weird so I opted not to enforce this.

So as I said, either you should implement something to restrict or queue dialogs, or if you know a dialog is already open, attach a `Class` to it like:
```C#
contentDialog.Classes.Add("noDarkArea");
```
and then use a Style Selector to take the background out:
```Xaml
<Style Selector="ContentDialog.noDarkArea /template/ Panel#LayoutRoot">
    <Setter Property="Background" Value="..." />
</Style>
```

**Comment by mysteryx93** [comment]
Makes sense. It could be a "nice" feature of MvvmDialogs if I decide to enforce this.
