### ISSUE TITLE
CalendarDatePicker - Calendar doesn't show when click on calendar button

### ISSUE THREAD

**Issue by yukina3230** [amwx/FluentAvalonia#308]
**Describe the bug**
When i click the calendar button on the right, the calendar doesn't show up

**Screenshots**
![image](https://user-images.githubusercontent.com/75545944/219585001-6280a839-d264-4a3e-bcd2-73d31abd3cb5.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version: 2.0.0-preview5
 - Avalonia Version: 11.0.0-preview5

**Additional context**
This control works normally in default avalonia theme

**Comment by amwx** [comment]
Should've been fixed upstream by https://github.com/AvaloniaUI/Avalonia/pull/10252
