### ISSUE TITLE
NumberBox does not update bound property.

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#31]
Numberbox does not update the bound property when the value changes, even if TwoWay mode is set for it. This occurs for both autoproperties and full properties.

**Comment by amwx** [comment]
I've set the DirectProperty to two way binding by default now (included in v1.1.1) and that seems to have fixed the issue. Zero clue why this issue occurred though, I'm guessing probably some weirdness of DirectProperties themselves, I'll have to test that out some other time.

**Comment by emmauss** [comment]
is there any reason the numberbox textbox color was changed to black? it's almost illegible in dark theme.

**Comment by amwx** [comment]
> 
> 
> is there any reason the numberbox textbox color was changed to black? it's almost illegible in dark theme.

Entirely an accident from trying to fix something. It'll be fixed in the next release.
