### ISSUE TITLE
Exception "Transform is not invertible"

### ISSUE THREAD

**Issue by saibot75** [amwx/FluentAvalonia#315]
**Describe the bug**
I get a crash when opening one of my ContentDialogs, had no problem in preview 5. I can work around the crash
by instructing ListBox to use StackPanel instead of default VirtualizingStackPanel.

**Desktop/Platform (please complete the following information):**
 - Windows 10
 - FluentAvalonia Version 2 preview 5.1
 - Avalonia Nightly 11.0.999-cibuild0030643-beta

Usercontrol for testing. I use the following code for opening:
private async void TestButton_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
{
	var dialog = new ContentDialog()
	{
		Title = "test",
		Content = new UserControl1(),
		CloseButtonText = "Close",
		PrimaryButtonText = "Primary",
		SecondaryButtonText = "Secondary",
		DefaultButton = ContentDialogButton.Close,
		IsPrimaryButtonEnabled = true,
		IsSecondaryButtonEnabled = true,
		FullSizeDesired = true
	};
	await dialog.ShowAsync();
}
[UserControl1.axaml.zip](https://github.com/amwx/FluentAvalonia/files/10847223/UserControl1.axaml.zip)

**Comment by amwx** [comment]
This is the where it goes bad in `ContentDialog`:
https://github.com/amwx/FluentAvalonia/blob/8636ee6ed41420ea93b93a1b6011999768330f83/src/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L196

In the past, there's been issues with items loaded into the `OverlayLayer` not applying their template/initializing until a layout pass happens, so there's this little trick (which is used upstream too). I took that out and the dialogs didn't crash like they used to and seemed fine, but I'm hesitant that this is the solution b/c I don't want to reintroduce the crash. I'm more curious though where this regressed in the nightly builds between preview5 and 5.1, as that might have a better answer.
