### ISSUE TITLE
MenuItem children are vertically and horizontally centered with parent [2-preview6]

### ISSUE THREAD

**Issue by stevemonaco** [amwx/FluentAvalonia#322]
**Describe the bug**
Seems to be a regression from 2-preview5. Vertical centering issue is upstream in https://github.com/AvaloniaUI/Avalonia/issues/10765 but the horizontal centering may be a separate issue as it only occurs in FA. I get similar horizontal centering in the FluentAvaloniaSamples Menu page built on master (but not on 2-preview5).

```xml
<Grid RowDefinitions="auto,*">
    <Menu>
        <MenuItem Header="First">
            <MenuItem Header="First.A" />
            <MenuItem Header="First.B">
                <MenuItem Header="First.B.1" />
                <MenuItem Header="First.B.2" />
                <MenuItem Header="First.B.3">
                    <MenuItem Header="First.B.3.a" />
                    <MenuItem Header="First.B.3.b" />
                    <MenuItem Header="First.B.3.c" />
                </MenuItem>
                <MenuItem Header="First.B.4" />
                <MenuItem Header="First.B.5" />
            </MenuItem>
            <MenuItem Header="First.C" />
        </MenuItem>
        <MenuItem Header="Second">
            <MenuItem Header="Second.A" />
            <MenuItem Header="Second.B" />
        </MenuItem>
    </Menu>
</Grid>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1782158/227249047-0dd77db7-c7d7-48b5-99ca-1afb2b675c05.png)

**Desktop/Platform (please complete the following information):**
 - OS: Win10
 - 2-preview6
 - 11-preview6

**Comment by robloo** [comment]
Flyout default position was changed upstream. I had to fix Menu as well: https://github.com/AvaloniaUI/Avalonia/pull/10667
