### ISSUE TITLE
NavigationView control showing up blank on Android when compiled in release mode

### ISSUE THREAD

**Issue by TheXamlGuy** [amwx/FluentAvalonia#326]
Take this example NavigationView from the Samples app:

```
   <ui:NavigationView
        x:Name="nvSample5"
        Height="460"
        Header="This is Header Text"
        IsSettingsVisible="False"
        IsTabStop="False">
        <ui:NavigationView.MenuItems>
            <ui:NavigationViewItem
                Content="Browse"
                IconSource="Library"
                Tag="SamplePage1" />
            <ui:NavigationViewItem
                Content="Track an Order"
                IconSource="Map"
                Tag="SamplePage2" />
            <ui:NavigationViewItem
                Content="Order History"
                IconSource="Tag"
                Tag="SamplePage3" />
        </ui:NavigationView.MenuItems>
        <ui:NavigationView.FooterMenuItems>
            <ui:NavigationViewItem
                Content="Account"
                IconSource="Contact"
                Tag="SamplePage4" />
            <ui:NavigationViewItem
                Content="Your Cart"
                IconSource="Shop"
                Tag="SamplePage5" />
            <ui:NavigationViewItem
                Content="Help"
                IconSource="Help"
                Tag="SamplePage6" />
        </ui:NavigationView.FooterMenuItems>
    </ui:NavigationView>
```

- Running it in debug mode on desktop, NavigationView displays as normal.
![image](https://user-images.githubusercontent.com/14894973/228025046-7ee22a2a-36fa-4afe-a962-1ea251a784da.png)

- Running it in release mode on desktop NavigationView displays as normal.
![image](https://user-images.githubusercontent.com/14894973/228024765-b45c92f4-9da0-4602-a201-1925a50132f4.png)

- Running it in debug mode on Android, NavigationView displays as normal.
![image](https://user-images.githubusercontent.com/14894973/228025923-de7532cf-9bae-49bf-898d-bc52285ff059.png)

- Running it in release mode on desktop, NavigationView does not render at all.
![image](https://user-images.githubusercontent.com/14894973/228028457-73c72f8e-bebd-4305-87fd-74b02b358bda.png)

Other controls such as the FAComboBox are rendering as normal on Android under release mode. No exceptions showing in the output log.

Using FluentAvaloniaUI 2.0.0-preview6 on .net7.0.

**Comment by TheXamlGuy** [comment]
I have an update on this after investigation some further and I have extracted a crash log from Android... not quite exactly sure what is happening though however. 

[log.txt](https://github.com/amwx/FluentAvalonia/files/11407621/log.txt)

**Comment by amwx** [comment]
This seems to be trimming related, please see if #356 fixes the issue (it does for me). You can use the preview7.2 nuget which requires Avalonia CI build 11.0.999-cibuild0034035-beta.

**Comment by WidgetifyApp** [comment]
> This seems to be trimming related, please see if #356 fixes the issue (it does for me). You can use the preview7.2 nuget which requires Avalonia CI build 11.0.999-cibuild0034035-beta.

Thanks for the update. Will give you an update on this tomorrow (9th).

**Comment by TheXamlGuy** [comment]
> > This seems to be trimming related, please see if #356 fixes the issue (it does for me). You can use the preview7.2 nuget which requires Avalonia CI build 11.0.999-cibuild0034035-beta.
> 
> Thanks for the update. Will give you an update on this tomorrow (9th).

Sorry, that was me logged on to another Git for the app. Can confirm all is now working! Issue can be closed.
