### ISSUE TITLE
NavigationView FooterMenuItems Error

### ISSUE THREAD

**Issue by rmbadmin** [amwx/FluentAvalonia#33]
When I set the NavigationView.FooterMenuItems property

When run, an exception occurs at https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/UI/Controls/NavigationView/NavigationView.cs#L816.

Why the code comments :
https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/UI/Controls/NavigationView/NavigationView.cs#L804

After I uncomment it, there is no problem

**Comment by amwx** [comment]
Fixed in v1.1.2
