### ISSUE TITLE
Cannot compile WASM since preview 5 (Not sure on version)

### ISSUE THREAD

**Issue by saibot75** [amwx/FluentAvalonia#333]
Since version preview 5 I cannot compile WASM anymore. I get this error:

The return type 'FluentAvalonia.Interop.Win32.LRESULT' of pinvoke callback method 'FluentAvalonia.Interop.Win32.LRESULT WndProcStatic(FluentAvalonia.Interop.Win32.HWND, System.UInt32, FluentAvalonia.Interop.Win32.WPARAM, FluentAvalonia.Interop.Win32.LPARAM)' needs to be blittable.  AvaloniaApplication1.Browser  C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.4\Sdk\WasmApp.Native.targets  290  

This just "happened" after the upgrade to FluentAvalonia and Avalonia. I cannot even compile the Avalonia Greetings template anymore.

**Comment by satial-interfaces** [comment]
I can confirm this. I removed private static LRESULT WndProcStatic(HWND hwnd, uint msg, WPARAM wParam, LPARAM lParam) for now, so WASM is up again. 

I must say: it looks stunning in the browser!

**Comment by robloo** [comment]
It might be a result of the separate windowing package being pulled in to the main one.
