### ISSUE TITLE
Content Dialog Fade doesn't cover all of the UI when settings MaxHeight

### ISSUE THREAD

**Issue by ArchLeaders** [amwx/FluentAvalonia#339]
**Describe the bug**
When the MaxHeight property is set, the content dialog won't fade (darken) the entire UI behind it.

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/80713508/232171823-e761c326-2c5b-4b96-bd92-38fb1f57fa48.png">

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version latest
 - Avalonia Version 11.0.0-preview6

**Comment by amwx** [comment]
The darkened background is part of the dialog template so if you restrict the size its going to affect that too. You'll have to use a custom style selector to target the actual dialog root element to do this (should be a Border IIRC - you'll have to look at the template). Or I think you can also override the resources `ContentDialogMaxHeight` to whatever you want and that should work too.
