### ISSUE TITLE
ListBox hover / selected effect does not follow the size of the LisBox Item 

### ISSUE THREAD

**Issue by ramzouza** [amwx/FluentAvalonia#343]
**Describe the bug**
If you change the width of the ListBox items, the `hover `and `selected `effects do not resize with the ListBoxItems. 
**Screenshots**

**Desktop/Platform:**
 - OS: Windows 10
 - FluentAvalonia Version: 2.0.0-preview6
 - Avalonia Version: 11.0.0-preview6

**Additional context**

**Comment by timunie** [comment]
@ramzouza the screenshots were lost. Can you add them again?

**Comment by amwx** [comment]
Likely related to the `MinWidth` on the ListBoxItem. I'm not sure if I want to remove that for ListBoxItem like I did with the other controls, so you'll either need to override the resource (which you can get from the ControlTheme) or use a style selector to override the ListBoxItem MinWidth to 0 for your project.
