### ISSUE TITLE
Combobox display issues after upgrading to Preview7

### ISSUE THREAD

**Issue by rmbadmin** [amwx/FluentAvalonia#350]
Describe the bug

After updating to Avalonia preview7, the ComboBox control is not displaying correctly. The scrollbar becomes stuck and doesn't change when it should, and the last option is not displayed when the ComboBox is expanded for the first time.

To Reproduce

Create a ComboBox control.
Populate it with several options.
Scroll down in the ComboBox and notice that the scrollbar gets stuck.
Expand the ComboBox and notice that the last option is missing.
Expected behavior

The ComboBox control should display all the options correctly, and the scrollbar should move smoothly without getting stuck.

Screenshots
![image](https://user-images.githubusercontent.com/12234359/234413727-80e3bdb9-bd9b-4808-9b09-7a8882d5581e.png)

Desktop/Platform

OS: Windows 11
FluentAvalonia Version: 2.0.0-preview7
Avalonia Version: Preview7

**Comment by amwx** [comment]
Believe its the same as https://github.com/AvaloniaUI/Avalonia/issues/11017, which is probably ItemsControl related and out of my hands.
