### ISSUE TITLE
crash when restoring from minimized window

### ISSUE THREAD

**Issue by ptpt666** [amwx/FluentAvalonia#353]
**Describe the bug**
When restoring from the minimized window, a crash occurs ,a nullreferenceexception is thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/6055564/234820422-b0c12181-2c40-4e59-b8db-8a5dc99389c8.png)

**Desktop/Platform (please complete the following information):**
 - OS:windows 10
 - FluentAvalonia Version 2.0.0-preview7
 - Avalonia Version 11.0.0-preview7

**Comment by PhantomGamers** [comment]
I can confirm I'm having this issue with my app [SFP](https://github.com/PhantomGamers/SFP) as well.

**Comment by amwx** [comment]
Fixed in preview7.1 (requires Avalonia CI build) or will be available in the next official preview release
