### ISSUE TITLE
Editable `FAComboBox` TextPresenter wrong colour

### ISSUE THREAD

**Issue by IsaacMarovitz** [amwx/FluentAvalonia#360]
**Describe the bug**
The TextPresenter of `FAComboBox` does not follow theme correctly.

**Screenshots**
<img width="264" alt="Screenshot 2023-05-08 at 20 13 26" src="https://user-images.githubusercontent.com/42140194/236962955-47b8ca63-8b1d-4356-b12f-bcbecd8d101a.png">

**Desktop/Platform (please complete the following information):**
 - OS: macOS
 - FluentAvalonia Version: 2.0.0-preview7.2
 - Avalonia Version: 11.0.999-cibuild0034035-beta

**Comment by amwx** [comment]
Fix will be in preview8. Turns out `TargetNullValue` in a {Binding} doesn't support `DynamicResource` which was causing a lookup to fail and foreground was defaulting to the default (light) theme.
