### ISSUE TITLE
Allowed Assing IconSource to Image.Source

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#362]
It simplifies image management in many circumstances

**Comment by amwx** [comment]
`IconSource` ends up translating to an IconElement when used which is a control and not an IImage, so its incompatible.

IIRC when I first implemented IconElements (this is way back either right before or early days of FluentAvalonia) I did have them as IImage, but it ended up making a lot of things much more complicated (don't remember specifics) so I changed it to follow WinUI making them controls.
