### ISSUE TITLE
`ComboBoxes` dont update when theme changes

### ISSUE THREAD

**Issue by IsaacMarovitz** [amwx/FluentAvalonia#366]
**Describe the bug:**
When the theme variant is changed from dark to light or light to dark, ComboBoxes's text presenters don't update their foreground colour.

**Screenshots:**
<img width="1212" alt="Screenshot 2023-05-16 at 11 32 15" src="https://github.com/amwx/FluentAvalonia/assets/42140194/8f99f87a-bcbd-438d-98e2-af91669b7430">

**Desktop/Platform:**
 - OS: All Platforms
 - FluentAvalonia Version: 2.0.0-preview8
 - Avalonia Version: 11.0.0-preview8

**Comment by amwx** [comment]
I can't repro this. I've tested both the regular ComboBox and my FAComboBox and have no issues when switching themes.
