### ISSUE TITLE
Unnecessary scrollbars in Menus

### ISSUE THREAD

**Issue by IsaacMarovitz** [amwx/FluentAvalonia#368]
**Describe the bug:**
There are scrollbars in menus on Windows even if they are not necessary.

**Screenshots:**
![image](https://github.com/amwx/FluentAvalonia/assets/42140194/a2f61fd6-04f7-4666-a125-298ddff3f8b6)

**Desktop/Platform:**
 - OS: Windows 11
 - FluentAvalonia Version: 2.0.0-preview8
 - Avalonia Version: 11.0.0-preview8

**Comment by amwx** [comment]
This issue appears to be related to non-100% scaling, and I think it might be related to some of the recent changes to `ScrollViewer`. At 125% scaling, I was getting the extent to be 0.8dip bigger than the viewport causing the scrollbar to appear. Can you see if this repros in Avalonia's Fluent theme too?

**Comment by amwx** [comment]
Should be fixed by Avalonia 11916 (haven't tested, but looked related). Closing as fixed/not FA issue
