### ISSUE TITLE
Blurry Graphics on Linux

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#38]
See description at: https://github.com/AvaloniaUI/Avalonia/issues/6633

I believe it might be related to this library as using `ControlsVersion="1"` seems to not be as blurry as Version 2

**Comment by amwx** [comment]
On Linux I don't touch the fonts and it defaults to the system font, I believe. You can check that through DevTools. But I don't really see an issue in your screenshot. I don't know if the screenshot aliased some of the blurring out, but it looks fine to me.

**Comment by nlogozzo** [comment]
Yeah I guess it's just the fonts :man_shrugging:
