### ISSUE TITLE
Use Blur Effect for Dialog Overlays

### ISSUE THREAD

**Issue by robloo** [amwx/FluentAvalonia#384]
**Is your feature request related to a problem? Please describe.**

Avalonia itself now implements the Blur Effect. This can be used to approximate the overlay blur used in WinUI when a ContentDialog is shown.

However, this is a little tricky, in order for the blur to really work it can't be done on the overlay itself -- it must be applied to everything under it (as in WPF but WinUI was a lot easier here). This is a severe limitation; hopefully upstream gets AcrylicBrushes and the like that can blur in the future. That said, it should be possible to render the application window to a Bitmap, apply a blur to the bitmap, then show that blurred bitmap as the overlay backdrop underneath ContentDialog and the like.

It may even be possible to extract this as a "BlurOverlayControl" which will render what's behind it (simplest as the entire app window) to a bitmap and then blur it.

**Describe the solution you'd like**

As described above.

**Describe alternatives you've considered**

Wait for upstream to work more like WinUI.

**Additional context**

**Comment by amwx** [comment]
As far as I know ContentDialog doesn't use the acrylic brushes. I have experimented with and `AcrylicPanel/Border` type control using a `ICustomDrawOperation` in the past but its really tricky to get right, and I want to say had a measurable perf hit (though its been a long while since I did this so I don't really remember).

**Comment by robloo** [comment]
> As far as I know ContentDialog doesn't use the acrylic brushes.

Huh, I was remembering incorrectly! I just checked UWP and you are correct: it doesn't blur the background like I thought it did. FluentAvalonia functions the same as UWP/WinUI.

I'm going to close this issue since I was mistaken on upstream functionality. If blur is desired it will be done on the app side.
