### ISSUE TITLE
InfoBar: Informational is transparent

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#39]
When i set the severity to information I get the following result:
![image](https://user-images.githubusercontent.com/17648453/134527122-0f0bbf18-7c3d-412d-9823-e0304d5628fe.png)

Whereas the other severities are not transparent:
![image](https://user-images.githubusercontent.com/17648453/134527238-ef4cdfe9-810f-4fd4-8843-c8085ad7ccba.png)

Could we make the informational severity not transparent as well, to properly display notifications.

**Comment by amwx** [comment]
I've double checked and the color value is correct from WinUI, so this is a design decision from Microsoft for some reason. You might be able to get around this by placing the `InfoBar` in a panel or border with a background matching the window to give an opaque background. But as I'm trying to keep a 1:1 style match with WinUI, I won't be changing it unless they do.
