### ISSUE TITLE
NavigationView is very laggy when having sub child navitem

### ISSUE THREAD

**Issue by squirrelfeng123** [amwx/FluentAvalonia#390]
Hello, I'm binding NavigationViewItem from ViewModel like below. 
As I'm using the nested navItem, when I click the Nav which has children, it is very very laggy, takes 4-5 seconds to expand.

Is there any suggestion or solution to help me? Thanks a lot!

```
<ui:NavigationView x:Name="NavView1"
                       PaneDisplayMode="LeftCompact"
                       MenuItemsSource="{Binding NaviItems}"
                       FooterMenuItemsSource="{Binding FooterItems}"
                       SelectedItem="{Binding SelectedNavItem}"
                       IsBackEnabled="False"
                       IsSettingsVisible="False"
    >
        <ui:NavigationView.MenuItemTemplate>
            <DataTemplate DataType="{x:Type vm:NaviItem }">
                <ui:NavigationViewItem Content="{Binding Title}"  
                                       ToolTip.Tip="{Binding Tag}"
                                       IconSource="{Binding Icon}" 
                                       MenuItemsSource="{Binding Children}"/>
            </DataTemplate>
        </ui:NavigationView.MenuItemTemplate>
        
        <rxui:RoutedViewHost x:Name="RoutedViewHost1"
                             HorizontalAlignment="Stretch"  VerticalContentAlignment="Stretch" />
    </ui:NavigationView>
```

**Comment by amwx** [comment]
I need more info here. What is laggy? The pane opening or the NavigationViewItem expanding to show its children? If its the pane opening, there's nothing I can do here. Unfortunately, SplitView works by animating the Width property which means as the animation runs multiple Layout passes occur, which can lead to some stuttering. Ideally I'd like to fix this upstream, but there's some issues I ran into last time I looked into this. 
If its the NavigationViewItem expanding, I'll need a full repro as I'm not seeing any issues.
