### ISSUE TITLE
Animation for highlighting selected header in NavigationView

### ISSUE THREAD

**Issue by Leon99** [amwx/FluentAvalonia#403]
Would be great to have this animation implemented. It's a small detail but its absence really stands out.
![Taskmgr_CPJuDYMKnO](https://github.com/amwx/FluentAvalonia/assets/6840381/07cde05f-7ac6-44fe-a10d-aba0ea78d8d2)

**Comment by amwx** [comment]
I'm planning this at some point, but the CompositionAnimation system in Avalonia (which is needed for this) is still not where I'd like it to be to get this implemented properly.
