### ISSUE TITLE
How do i use native titlebar on windows on AppWindow

### ISSUE THREAD

**Issue by Eugenenoble2005** [amwx/FluentAvalonia#407]
When i set
```
        TitleBar.ExtendsContentIntoTitleBar = false;
```
It creates a custom title bar at the top of the window. How can i use it with the native title bar instead of the drawn one, I can extend the Avalonia window instead but then i wouldnt easily be able to use the splash screen.

**Comment by amwx** [comment]
You can't. Part of extending the client area into the frame is removal of the system titlebar, thus the need for a managed one. It still functions the same - including Win11 snap layouts.
