### ISSUE TITLE
TaskDialog.ShowAsync throws NullReferenceException

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#408]
Getting a NullReferenceException here

    DialogResult = await dialog.ShowAsync().ConfigureAwait(true);

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentAvalonia.UI.Controls.TaskDialog.ShowAsync(Boolean showHosted)
   at HanumanInstitute.MvvmDialogs.Avalonia.Fluent.FluentTaskView.ShowDialogAsync(IView owner)
```

Do note that the TaskDialog does show; the error throws after closing it.

Avalonia v11.0.0-rc1
FluentAvalonia v2.0.0-rc1

**Comment by amwx** [comment]
I can't reproduce any crash with TaskDialog. However, you've only included one line of your code from which I cannot determine where any errors may be arising. Please include enough context in sample code for me to diagnose or reproduce the issue, thanks.

This works for me:
```C#
 var td = new TaskDialog
{
    Title = "title",
    Content = "Content",
    XamlRoot = this,
    Buttons =
    {
        TaskDialogButton.OKButton
    }
};

var result = await td.ShowAsync().ConfigureAwait(true);
```
