### ISSUE TITLE
ContentDialog do not block keyboard input on background controls

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#419]
**Describe the bug**
ContentDialog do not block keyboard input on background controls

**Step to reproduce**
- Run `FAControlsGallery.Desktop`
- Go to `ContentDialog` page sample
- Set Default Button to `Primary`
- Click on button `Launch ContentDialog`
- Press `Enter` key on keyboard 

**Screenshots**

**Desktop/Platform (please complete the following information):**
 - OS: **independent**
 - FluentAvalonia Version: **master 31140cccf95f9af428d90767d9f192ed6c8492f5**
 - Avalonia Version: **11.0-rc1.1**

**Additional context**

**Comment by stevemonaco** [comment]
IIRC, `ContentDialog` doesn't automatically focus upon showing in FA. I worked around this by focusing the dialog, but you also have to be careful that `ContextMenu` popups don't steal focus back if you're launching a dialog from one.

```cs
public async Task AlertAsync(string title, string message)
{
    await Task.Yield(); // Yield ensures any ContextMenus are closed so focus isn't stolen

    var titleBlock = new SelectableTextBlock()
    {
        Text = title
    };

    var contentBlock = new SelectableTextBlock()
    {
        Text = message
    };

    var cd = new ContentDialog
    {
        PrimaryButtonText = "Ok",
        Title = titleBlock,
        Content = contentBlock,
        IsPrimaryButtonEnabled = true,
        IsSecondaryButtonEnabled = false,
        DefaultButton = ContentDialogButton.Primary
    };

    cd.AttachedToVisualTree += InitializeWithFocus;
    await cd.ShowAsync();
    cd.AttachedToVisualTree -= InitializeWithFocus;

    void InitializeWithFocus(object? sender, VisualTreeAttachmentEventArgs e)
    {
        cd.Focus();
    }
}
```

**Comment by amwx** [comment]
`ContentDialog` is supposed to focus the dialog upon opening - the code is there to do it, but for some reason its not working. The dialog is attached to the tree and the actual buttons are realized and .Focus is called, but for some reason the focus is either shifting back to whatever was originally focused or it never applies.

In all honesty, the way ContentDialog is setup is quite messy and has been hacked together to deal with some life cycle stuff that was an issue when it was originally written (this is one of the oldest controls in this library) - something that was improved with TaskDialog, and may have improved with 11.0. I'd like to try and refactor that to make it easier and more reliable, but I really want to get my unit tests back up first to ensure nothing breaks in that process, something I'm hoping to do later this summer. For now, I'd recommend manually focusing the dialog

**Comment by timunie** [comment]
https://github.com/amwx/FluentAvalonia/blob/9349a97fbd14a3e0a930042cfbf7962132d6c872/src/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L356

@amwx I think focus should happen on the UI thread and after loading is completed, so I guess wrapping it in `Dispather.UIThead.Post(() => btn.Focus, DispatcherPriority.Loaded)` should do the trick. At least I do it that way to focus a textbox in a custom ContentDialog.

**Comment by amwx** [comment]
> https://github.com/amwx/FluentAvalonia/blob/9349a97fbd14a3e0a930042cfbf7962132d6c872/src/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L356
> 
> @amwx I think focus should happen on the UI thread and after loading is completed, so I guess wrapping it in `Dispather.UIThead.Post(() => btn.Focus, DispatcherPriority.Loaded)` should do the trick. At least I do it that way to focus a textbox in a custom ContentDialog.

We are still on the UI thread when that is called though. Technically, we never leave the UI thread (or else we'd crash with invalid thread) except for the TaskCompletionSource that's used to await user input on the dialog.

I know this used to work, so I need to figure out why it stopped and what the best way to fix it is. Posting to the dispatcher working though does seem to suggest that maybe we're not entirely connected to the tree yet (as I thought). I have some ideas on this though...
