### ISSUE TITLE
[Bug] ComboBox List Border Not Shown Properly 

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#42]
It seems as there is an issue drawing the border around the list of a ComboBox:
![image](https://user-images.githubusercontent.com/17648453/134782316-872f914e-af7d-4880-9b10-119dc1c7b789.png)

However, this ComboBox seems to be fine:
![image](https://user-images.githubusercontent.com/17648453/134782319-46a1f0fe-2fe2-4a64-b15d-75abb8d8349e.png)

Here is my XAML:
```xml
<ui:ContentDialog xmlns="https://github.com/avaloniaui"
				  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
				  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
			      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
				  xmlns:ui="using:FluentAvalonia.UI.Controls"
				  xmlns:uip="using:FluentAvalonia.UI.Controls.Primitives"
				  xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
				  xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions"
				  mc:Ignorable="d" x:Class="NickvisionApp.Views.SettingsDialogView"
				  Name="SettingsDialog" Title="{Binding Title}"
				  CloseButtonText="Close" DefaultButton="Close" CloseButtonCommand="{Binding CloseCommand}">
	<ui:ContentDialog.Resources>
		<x:Double x:Key="ContentDialogMaxWidth">600</x:Double>
		<x:Double x:Key="ContentDialogMaxHeight">600</x:Double>
	</ui:ContentDialog.Resources>

	<ui:ContentDialog.Styles>
		<Style Selector="ui|ContentDialog /template/ Grid#DialogSpace">
			<Setter Property="Width" Value="440"/>
			<Setter Property="Height" Value="500" />
		</Style>
	</ui:ContentDialog.Styles>

	<StackPanel>
		<TextBlock Text="Theme" Margin="0,0,0,2"/>

		<ComboBox Width="200" Items="{Binding Themes}"/>
		
		<TextBlock Text="Accent Color" Margin="0,10,0,2"/>
		
		<ComboBox Width="200" Items="{Binding AccentColors}"/>
	</StackPanel>
</ui:ContentDialog>
```

**Comment by nlogozzo** [comment]
Could've just been a Linux rendering thing, seems to have been fixed with updates 🤷‍♂️ (I'm on Windows now so don't really know)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/154811245-1fa7a1a5-912a-4a03-b2b5-54556b38b7cd.png)

**Comment by nlogozzo** [comment]
Still occurring it looks like. this is on Windows 11

**Comment by amwx** [comment]
Related to `ComboBoxDropDownBorderBrush` being semi-transparent (mapped to SurfaceStrokeColorFlyout - #33000000), and the background behind the ComboBoxes happens to be the same as the popup background. Closing as 'by WinUI design' since no actual rendering issue is present
