### ISSUE TITLE
InfoBadge does not show in compact state when in NavigationView.PaneFooter without template

### ISSUE THREAD

**Issue by ionite34** [amwx/FluentAvalonia#425]
**Describe the bug**
Currently the `InfoBadge` does not show in compact states of `NavigationView` when it is defined in the `PaneFooter`. In the below images, the first "Downloads" item is defined in `PaneFooter` as a static element and the second one is a `MenuItemsSource` object with a DataTemplate in `MenuItemTemplate`. 

If this is supposed to be managed myself, I'm not sure how to go about dynamically switching the badge states from expanded to collapsed upon changing NavigationView states. 

- Collapsed NavigationView
<img width="90" alt="image" src="https://github.com/amwx/FluentAvalonia/assets/13956642/5e649f94-85cd-4eb0-97a0-3cce9c3bda4b">

- Expanded NavigationView
<img width="154" alt="image" src="https://github.com/amwx/FluentAvalonia/assets/13956642/6609f41c-8556-4d42-bed4-32b707a19d41">

**Comment by ionite34** [comment]
> NavigationView items should be placed in either `MenuItems/MenuItemsSource` or `FooterMenuItems/FooterMenuItemsSource`. Items added to things like `PaneFooter` are not visible to the NavigationView and thus don't know about changing states.

Is it possible to create a "button" type template for a menu item that opens a flyout / browser url without actual navigation pages? I was thinking of creating a dummy view model type for the footer button and associated DataTemplate, but that would still cause navigation to the empty content

**Comment by amwx** [comment]
How are you triggering navigation? Are you binding to SelectedItem, using the selection changed or item invoked events?

If you're using selection based triggers, you can create a NavigationViewItem with `SelectsOnInvoked` set to false to prevent that item from selecting, then handle the `ItemInvoked` event on the NavigationView to do whatever you want. The EventArgs give you the item and some other information to know which item was invoked and you can handle it accordingly.

If you're already using `ItemInvoked`, again just scan for your specific item and do whatever you want.
