### ISSUE TITLE
ContentDialog System.NullReferenceException:“Object reference not set to an instance of an object.”

### ISSUE THREAD

**Issue by gatspy** [amwx/FluentAvalonia#426]
version 2.0.0, avaloniaui version 11.0.0

```c#

        var cd = new ContentDialog
        {
            PrimaryButtonText = "确定",
            CloseButtonText = "取消",
            Title = "提示",
            Content = "您确定要退出应用吗?",
            IsPrimaryButtonEnabled = true,
            IsSecondaryButtonEnabled = false,
            DefaultButton = ContentDialogButton.Primary,
        };

        await cd.ShowAsync();
```
![image](https://github.com/amwx/FluentAvalonia/assets/804446/bb56e0c9-2fca-4853-8d63-b7f73a868ed0)

**Comment by noliar** [comment]
This problem may occur if the necessary `<sty:FluentAvaloniaTheme />`  is not added to **App.axaml** file.
[https://amwx.github.io/FluentAvaloniaDocs/pages/GettingStarted#styles](url)

**Comment by amwx** [comment]
Yes `FluentAvaloniaTheme` is required as it stores all of the theme/styling information for all the controls. Without that, there's nothing to display and required template components can't be found which could cause the NullReferenceException.
