### ISSUE TITLE
SettingsExpanderItem HorizontalContentAlignment

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#438]
**Describe the bug**
SettingsExpanderItem ignore  HorizontalContentAlignment settings

```xaml
            <ui:SettingsExpander IconSource="Globe" Header="Test Header" IsExpanded="True"
                                 Description="This is a description for the SettingsExpander"
                                 ActionIconSource="Save" IsClickEnabled="False">
                <ui:SettingsExpander.Footer>
                    <Button Content="FooterButton" />
                </ui:SettingsExpander.Footer>

                <ui:SettingsExpanderItem Content="Content Here" ActionIconSource="Pin" IsClickEnabled="True"  />
                <ui:SettingsExpanderItem Content="Content Here">
                    <ui:SettingsExpanderItem.Footer>
                        <Button Content="FooterButton" />
                    </ui:SettingsExpanderItem.Footer>
                </ui:SettingsExpanderItem>
                <ui:SettingsExpanderItem Content="Right Content Here" 
                                         HorizontalContentAlignment="Right"/>
            </ui:SettingsExpander>
```

**Screenshots**
 ## Current
![immagine](https://github.com/amwx/FluentAvalonia/assets/12531229/c72aa8f7-52fe-434f-a8ef-e23024a69cfa)

## Expected
![Senza nome](https://github.com/amwx/FluentAvalonia/assets/12531229/df26aa26-6948-403b-9fbd-8c383a3753b6)

**Desktop/Platform (please complete the following information):**
 - OS: any
 - FluentAvalonia Version **2.0.0**
 - Avalonia Version **11.0.0**

**Additional context**

**Comment by amwx** [comment]
This is by design. The content should be left aligned so that it aligns correctly with a description (if provided) and it usually functions as a "Title/Header". Items that should appear on the right should be placed in the Footer.

**Comment by workgroupengineering** [comment]
the main problem is that you can't stretch the content.  I made this example because it is more obvious.
