### ISSUE TITLE
Why I cant use FA in avalonia11

### ISSUE THREAD

**Issue by akchiji888** [amwx/FluentAvalonia#449]
After I updated Avalonia to 11.0.2, I cant use FA controls any more.
![258649734-dc2d1520-ca21-47a6-8bab-9a678f9734c4](https://github.com/amwx/FluentAvalonia/assets/92619820/404fe90c-d121-4cab-beeb-b1cbf2a0e2e9)
I have already used FA styles
![258649808-89236a14-9e90-4e1f-a611-949b75b3fcb6](https://github.com/amwx/FluentAvalonia/assets/92619820/52d313ff-af4d-4188-bd81-410500572c01)
![258649822-0c16cac0-f005-4098-9dea-d1d041b24f45](https://github.com/amwx/FluentAvalonia/assets/92619820/967a4af9-84e1-41f6-aaa2-6c1cdf3f08f1)
And I cant use the controls in C# files
This problem seems to be caused by avalonia generater, it cant generate FA comboboxes
or maybe my XAML code is wrong

**Comment by sccombp** [comment]
use FAComboBox instead of ComboBox

**Comment by akchiji888** [comment]
how to use that?
(I am a noob)

**Comment by sccombp** [comment]
change 
```csharp
<ui:ComboBox ...
```
to
```csharp
<ui:FAComboBox ...
```

**Comment by akchiji888** [comment]
Thank you very much! I have succeeded in solving the problem!
