### ISSUE TITLE
How to set an icon in NavigationView of FluentAvaloniaUI

### ISSUE THREAD

**Issue by Daniil-Kolbasov** [amwx/FluentAvalonia#462]
I want to install an icon from [FluentAvalonia.FluentIcons](https://github.com/taj-ny/FluentAvalonia.FluentIcons), where such a code is specified:

```xaml
<ui:NavigationView>
     <ui:NavigationView.MenuItems>
            <ui:NavigationViewItem Content="Page 1">
                <ui:NavigationViewItem.Icon>
                    <ic:FluentIcon Icon="Settings16Filled"/>
                </ui:NavigationViewItem.Icon>
            </ui:NavigationViewItem>

            <!-- The library also provides markup extensions to reduce boilerplate code -->
            <ui:NavigationViewItem Content="Page 2"
                                   Icon="{ic:FluentIcon Settings16Regular}"/>
        </ui:NavigationView.MenuItems>
</ui:NavigationView>
```
But this code causes an error for me: Unable to resolve type FluentIcon from namespace using:FluentAvalonia.FluentIcons

![image](https://github.com/amwx/FluentAvalonia/assets/34882813/efa41be3-a53f-49de-9fcd-ce28e69940d5)

What am I doing wrong?

**Comment by timunie** [comment]
I guess it's not up to date with 11.0 and FA 2.0: 
https://github.com/taj-ny/FluentAvalonia.FluentIcons/blob/0e91c4b66a205953e65e7754e65aebb738ceab60/FluentAvalonia.FluentIcons/FluentAvalonia.FluentIcons.csproj#L39

**Comment by amwx** [comment]
As already said that library hasn't been updated to support v2 yet. This should be reported on that repo (as I'm not the maintainer). Closing as unrelated to FluentAvalonia
