### ISSUE TITLE
Weird visual glitches on Linux

### ISSUE THREAD

**Issue by NotroDev** [amwx/FluentAvalonia#464]
**Describe the bug**
Hi!
I created a simple layout for my app.
It works fine on Windows, but on Linux, it has a weird "visual glitches". It seems that they are appearing when I hover the TabView.
If I run the sample app, it all glitches like this.

I'm running the Linux on a virtual machine, so maybe this is a problem. I asked a friend to test it on his Linux PC, so when he'll do it, I'll write an update.

Code: https://pastebin.com/26N03444

**Screenshots**
![obraz](https://github.com/amwx/FluentAvalonia/assets/77281214/581ab8d7-9d88-4ff2-aaa3-58d35c49593b)
![Screenshot from 2023-08-21 09-37-42](https://github.com/amwx/FluentAvalonia/assets/77281214/2af9c902-ed12-4343-9c72-aafc7d3cf3cf)
![Screenshot from 2023-08-21 09-37-59](https://github.com/amwx/FluentAvalonia/assets/77281214/46ae2141-a3cd-4d83-847b-fc58ad9868db)

**Desktop/Platform**
 - OS: Ubuntu 22.04.3 64-bit
 - FluentAvalonia 2.0.1
 - Avalonia 11.0.4

**Comment by amwx** [comment]
I don't really know what's going on in the first screenshot. For the menu, if the white background appears behind popups, it means your OS doesn't support transparent windows (or that isn't enabled at least). This I can't do anything about as this not an Avalonia thing.

I'm not a linux expert, especially with non-mainstream distros so unfortunately there's not much help I can offer here

**Comment by NotroDev** [comment]
> I don't really know what's going on in the first screenshot. For the menu, if the white background appears behind popups, it means your OS doesn't support transparent windows (or that isn't enabled at least). This I can't do anything about as this not an Avalonia thing.
> 
> I'm not a linux expert, especially with non-mainstream distros so unfortunately there's not much help I can offer here

Hmmm... Okay. I installed Lubuntu because I thought it was pretty popular and small. I'll try to install normal Ubuntu and see if it happens.

**Comment by NotroDev** [comment]
> I don't really know what's going on in the first screenshot. For the menu, if the white background appears behind popups, it means your OS doesn't support transparent windows (or that isn't enabled at least). This I can't do anything about as this not an Avalonia thing.
> 
> I'm not a linux expert, especially with non-mainstream distros so unfortunately there's not much help I can offer here

I installed an Ubuntu 22.04.3 Desktop amd64 and problem still persists :/
It works perfectly fine on Windows, and on Linux it worked too when I used pure Avalonia.
As I said, the problem is probably with the TabView (because it only happens when I hover on it/drag it)

**Comment by amwx** [comment]
I slightly misspoke, its not the OS not supporting transparency, its the Window Manager. 

I just tested the sample app on Ubuntu (which uses the default Gnome window manager) and I have no issues, so both issues I'm guessing are tied to whatever window manager you're using. Still not sure how the first issue relates to that - unless Skia/OpenGL doesn't like said window manager.

Is it just hover, or is it drag specific. When dragging a tab, it goes invisible during the reorder/drag operation and that may be triggering some sort of rendering glitch? Still not entirely sure.

**Comment by NotroDev** [comment]
> I slightly misspoke, its not the OS not supporting transparency, its the Window Manager.
> 
> I just tested the sample app on Ubuntu (which uses the default Gnome window manager) and I have no issues, so both issues I'm guessing are tied to whatever window manager you're using. Still not sure how the first issue relates to that - unless Skia/OpenGL doesn't like said window manager.
> 
> Is it just hover, or is it drag specific. When dragging a tab, it goes invisible during the reorder/drag operation and that may be triggering some sort of rendering glitch? Still not entirely sure.

The white background is working fine, sorry, I didn't mention that.

I'll try to use the sample app and see if it works.

This happens when I hover on it, and honestly I don't know if dragging have something to do with it, because, well, to drag you need to hover. I'll try to record it too.

**Comment by NotroDev** [comment]
The entire sample app is glitching like this on Umu buntu. Maybe it's because of vmware? I don't know. I have a friend with Linux, I'll ask him to test it.

**Comment by timunie** [comment]
@NotroDev looks like transparency is disabled on your VM machine.

**Comment by NotroDev** [comment]
> @NotroDev looks like transparency is disabled on your VM machine.

But on Ubuntu, the Menu looks normal and has a transparent background. The only problem now is the first mentioned in the issue

**Comment by NotroDev** [comment]
> Are you using the software rendering backend (or no GPU) for your app? Basically we don't support transparency on platforms without a GPU.

I don't understand. Where I can check it? And also:
> But on Ubuntu, the Menu looks normal and has a transparent background. The only problem now is the first mentioned in the issue

So it probably doesn't matter anymore

**Comment by timunie** [comment]
@NotroDev in that case please update the issue description carefully. Thx.

**Comment by timunie** [comment]
@NotroDev I've asked the avalonia core team and they said that running in a VM is a valid thing. However I got this response: 
> "Probably need to blacklist gpu driver"

As I'm not a linux expert, can't say anything how to achieve it. But maybe you can google around and give it a try.

**Comment by NotroDev** [comment]
> @NotroDev I've asked the avalonia core team and they said that running in a VM is a valid thing. However I got this response:
> 
> > "Probably need to blacklist gpu driver"
> 
> As I'm not a linux expert, can't say anything how to achieve it. But maybe you can google around and give it a try.

Thanks! I'll try :)
