### ISSUE TITLE
ContentDialog is not working under android after 2.01

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [amwx/FluentAvalonia#466]
**Describe the bug**
A clear and concise description of what the bug is and any steps to reproduce it. Sample code or a minimal repro is helpful.

    ContentDialog() is not working under android 

    try
    {
        result = await ShowDialog("Warning", "This message only shows in windows. In Android it generate an exception !") !
    } 
    catch (Exception ex)
    {
    }

    public static async Task<ContentDialogResult> ShowDialog(string Titulo, string Mensagem)
    {
        return await (new ContentDialog()
        {
            Content = Mensagem,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            HorizontalContentAlignment = HorizontalAlignment.Stretch,
            PrimaryButtonText = "OK",
            Title = Titulo
        }).ShowAsync();
    }

**Screenshots**

![image](https://github.com/amwx/FluentAvalonia/assets/138352584/0b5e0c12-8076-40af-9507-1b37fb8b983a)

![image](https://github.com/amwx/FluentAvalonia/assets/138352584/e4d2750e-a1e5-49aa-8a9f-7536ede7d396)

**Desktop/Platform (please complete the following information):**
 - OS: [e.g. Windows (11/10), linux (distro), osx, wasm, etc]
    Android Emulator 33
    Avalonia 11.4
    FluentAValonia 2.0.1

**Additional context**

**Comment by timunie** [comment]
better to specify actual TopLevel: 

https://github.com/amwx/FluentAvalonia/blob/4d847a8403b914d558baa79351a7866a02ec0b3e/src/FluentAvalonia/UI/Controls/ContentDialog/ContentDialog.cs#L139-L145

That way you have much more control over where it is shown.

**Comment by amwx** [comment]
I think was fixed in #457, if the error is occurring on something related to focus (your screenshots don't include any line numbers). This fix just hasn't been pushed out to a package yet, and I'm not sure when I'll be able to push the next one.

Specifying the TopLevel \*should\* fix this in the meantime, as not specifying one works by attempting to find one via the ApplicationLifetime and there was an issue there with ISingleViewApplicationLifetime (which Android uses)

**Comment by sccombp** [comment]
This also happens under WASM, I can confirm that setting the TopLevel worked.

**Comment by amwx** [comment]
This should be fixed by #479 and v2.0.4. If it does not, feel free to reopen.
