### ISSUE TITLE
Problems with SymbolIcon in MenuItem.Icon

### ISSUE THREAD

**Issue by NotroDev** [amwx/FluentAvalonia#468]
**Describe the bug**
Hello. I don't know if this is a bug, or if I'm doing something wrong, but I can't set the size of SymbolIcon in MenuItem.Icon property correctly.
When I have Width and Height set to 60, and FontSize to 75, it's the best result that I can get, but the OpenFile icon gets cropped. When I'm trying to set Width and Height to 70 to fix it, icons get small. The same happens if I set it to Auto.

My code:
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			 xmlns:ui="using:FluentAvalonia.UI.Controls"
			 x:Class="MyProject.Controls.MainMenuControl">

	<UserControl.Styles>
		<Style Selector="ui|SymbolIcon">
			<Setter Property="Width" Value="60"/>
			<Setter Property="Height" Value="60"/>
			<Setter Property="FontSize" Value="75"/>
		</Style>
	</UserControl.Styles>
	
	<Menu Name="MainMenu">
		<MenuItem Header="{DynamicResource MenuHeaderFile}">
			<MenuItem Header="New" Name="MenuItemNew" HotKey="Ctrl+N" InputGesture="Ctrl+N">
				<MenuItem.Icon>
					<ui:SymbolIcon Symbol="Add"/>
				</MenuItem.Icon>
			</MenuItem>
			<MenuItem Header="Open" Name="MenuItemOpen" HotKey="Ctrl+O" InputGesture="Ctrl+O">
				<MenuItem.Icon>
					<ui:SymbolIcon Symbol="OpenFile"/>
				</MenuItem.Icon>
			</MenuItem>
	</Menu>
</UserControl>
```

**Screenshots**
`Width,Height = 60 | FontSize = 75`
![obraz](https://github.com/amwx/FluentAvalonia/assets/77281214/fd9b7783-002e-4a39-9e7a-f6b0b5d2f276)
`Width,Height = 70 | FontSize = 75`
![obraz](https://github.com/amwx/FluentAvalonia/assets/77281214/f67584f7-5f35-4f3f-8d82-c992c41622f6)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - Latest FluentAvalonia
 - Avalonia 11.0.4

**Comment by timunie** [comment]
when in doubt, check original styles, in your case for MenuItem I guess

**Comment by NotroDev** [comment]
Okay, I fixed it with custom MenuItem style.
