### ISSUE TITLE
Styling - Checkbox check glyph is a bit too thin compared to WinUI

### ISSUE THREAD

**Issue by ionite34** [amwx/FluentAvalonia#473]
Checkbox checkmark is a bit too thin and hard to see currently.

Left is FluentAvalonia, Right is WinUI 3 (Windows Settings)
![](https://github.com/amwx/FluentAvalonia/assets/13956642/f1c24b05-18fa-4045-81c3-403ce23a62f3)

Perhaps using the filled variant of the Checkmark glyph would bring it more in-line with WinUI?

**Comment by amwx** [comment]
WinUI has switched to using their `AnimatedIcon` for the Check glyph, which has a slightly thicker rendering. The fallback glyph, though, is still the symbol font which will look nearly identical to what we have now.
