### ISSUE TITLE
NavigationView Tooltips on touch screens

### ISSUE THREAD

**Issue by tobyfirth** [amwx/FluentAvalonia#474]
**Is your feature request related to a problem? Please describe.**
When using a touch screen as the input method tooltips are not particularly useful. They some times though appear when a user touches one of the navigation elements. The tooltip then stays on the screen even if the user touches something. It is a minor inconvenience really but it does confuse some users.

**Describe the solution you'd like**
It would be nice if there was a way to disable all tooltips as a property on the NavigationView. I see that in NavigationViewItem there is a property already which enables/disables tooltips so I think part of a solution is already there.

**Describe alternatives you've considered**
This might be an issue with the way Avalonia treats touch inputs which erroneously triggers a mouse hover and thus triggering the appearance of the tooltip.

Hopefully something can be worked out and thank you for the work you do on this library.

**Comment by amwx** [comment]
> This might be an issue with the way Avalonia treats touch inputs which erroneously triggers a mouse hover and thus triggering the appearance of the tooltip.

This sounds like a bug in the touch-related code in Avalonia. It might be better to create a minimal repro using just Avalonia controls (like a ListBox or Button with a ToolTip - this just keeps the example simple) and open an issue upstream
