### ISSUE TITLE
Frame.Navigate() doesn't work on Linux

### ISSUE THREAD

**Issue by NotroDev** [amwx/FluentAvalonia#483]
**Describe the bug**
Hi. I created a Window with:
```xml
<ui:Frame Name="FrameView">
	<sv:HomePage/>
</ui:Frame>
```
It works well on any system. The problem is with Navigate(). In HomePage, I have a button and Command associated to it:
```cs
PersonalizationItem.Command = new RelayCommand(() =>
{
	SettingsWindow.Instance.FrameView.Navigate(typeof(PersonalizationPage), null, new EntranceNavigationTransitionInfo());
});
```
It works perfectly on Windows, but on Linux, nothing happens.
When I have an empty Frame, and I put a `FrameView.Navigate(typeof(HomePage))` in SettingsWindow's constructor, it works on Windows, but on Linux there is an empty window.

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11/Ubuntu 22.04
 - FluentAvalonia v2.0.4
 - Avalonia Version 11.0.4

**Comment by sccombp** [comment]
I ran into the same issue when I updated to the latest version of Avalonia (11)

try the following code
```csharp
PersonalizationItem.Command = new RelayCommand(() =>
{
        var navOpt = new FrameNavigationOptions() { TransitionInfoOverride = new EntranceNavigationTransitionInfo() };
	SettingsWindow.Instance.FrameView.NavigateToType(typeof(PersonalizationPage), null, navOpt);
});
`

**Comment by NotroDev** [comment]
> I ran into the same issue when I updated to the latest version of Avalonia (11)
> 
> try the following code
> 
> ```cs
> PersonalizationItem.Command = new RelayCommand(() =>
> {
>         var navOpt = new FrameNavigationOptions() { TransitionInfoOverride = new EntranceNavigationTransitionInfo() };
> 	SettingsWindow.Instance.FrameView.NavigateToType(typeof(PersonalizationPage), null, navOpt);
> });
> `
> ```

Hey, thanks for your reply!
It doesn't work for me :/
The same problem, nothing happens (works on Windows).

**Comment by NotroDev** [comment]
For some reason, it works now (I think).
Maybe it was caused by using VM.
