### ISSUE TITLE
How can we set content on CommandBarToggleButton

### ISSUE THREAD

**Issue by Eugenenoble2005** [amwx/FluentAvalonia#485]
It seems the CommandBarToggleButton can only have a text and icon content set by the label and iconSource property respectively. How can we set custom content using the Content property like we can on the ToggleButton Control. I would have just used the ToggleButton Control, but the CommandBar children requires a commandBarToggleButton instead of a normal ToggleButton.

**Comment by timunie** [comment]
override the ControlTemplate to your needs. See: https://github.com/amwx/FluentAvalonia/blob/759d12a67f623a15f44c18c10e0e7480a69aa8e1/src/FluentAvalonia/Styling/ControlThemes/FAControls/CommandBar/CommandBarButtonStyles.axaml#L68-L150

**Comment by Eugenenoble2005** [comment]
Thanks Tim!
