### ISSUE TITLE
Button ignore TextElement.FontSize

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#488]
## Describe the bug
If you set the `TextElement.FontSize` of a Button container, the button will not honor the setting.

## How reproduce:
- Copy the following xaml in FASandbox

```xaml
    <UniformGrid Columns="2"
                 HorizontalAlignment="Left"
                 VerticalAlignment="Top"
                 TextElement.FontSize="50">
        <Button Content="AAAA"
                />
        <TextBlock Text="AAAA"
                   VerticalAlignment="Center"/>
    </UniformGrid>
```

### FASandbox
![immagine](https://github.com/amwx/FluentAvalonia/assets/12531229/ca690f39-1e87-44eb-afb8-fe359172b94b)

### Avalonia Sandbox

![immagine](https://github.com/amwx/FluentAvalonia/assets/12531229/02dcae5e-ae63-4a81-ae8d-d8cb36869ccb)

## Desktop/Platform
 - OS: **any**
 - FluentAvalonia Version: **2.0.4**
 - Avalonia Version: **11.0.4**

**Additional context**

**Comment by timunie** [comment]
FontSize is set via DynamicResource here: https://github.com/amwx/FluentAvalonia/blob/759d12a67f623a15f44c18c10e0e7480a69aa8e1/src/FluentAvalonia/Styling/ControlThemes/BasicControls/ButtonStyles.axaml#L30

Overriding the resource will update button font size
