### ISSUE TITLE
Cannot aot in.net8

### ISSUE THREAD

**Issue by wj8400684** [amwx/FluentAvalonia#492]
Cannot aot in.net8

**Comment by hez2010** [comment]
Which version of FluentAvalonia are you using? We have fixed the trimming issue around `FALocalizationHelper` a while ago.

**Comment by wj8400684** [comment]
2.04

**Comment by crackedmind** [comment]
For .net 8 workaround for now is set <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault> in your project.
