### ISSUE TITLE
Android (only) not following RequestedThemeVariant

### ISSUE THREAD

**Issue by metal450** [amwx/FluentAvalonia#497]
* Previously I was using `<FluentTheme/>` with `RequestedThemeVariant="Dark"` in a Windows+Android project, and it showed in Dark  Mode as intended.
* Upon installing FluentAvalonia and replacing `<FluentTheme/>` with `<sty:FluentAvaloniaTheme/>`, the theme is Dark Mode on Windows (as expected), but remains Light Mode on Android.
* The Android device itself has its system set to Dark Mode, but I also tried explicitly using `<sty:FluentAvaloniaTheme PreferSystemTheme="False" />`, and it still remains in Light Mode on Android.
* I also tried running it in the Android emulator, and like on the physical device, it remains in Light Mode.

How can I get Android to respect `RequestedThemeVariant="Dark"`, as it does on Windows?

I made no changes other than:
* Add the FluentAvaloniaUI nuget package
* Add `xmlns:sty="using:FluentAvalonia.Styling"` and `<sty:FluentAvaloniaTheme />` to `<Application>`

**Desktop/Platform (please complete the following information):**
 - FluentAvalonia Version 2.0.4
 - Avalonia Version 11.0.5

**Comment by Ricent82** [comment]
Workaround: it looks like if I set `Application.Current.RequestedThemeVariant = ThemeVariant.Dark;` programmatically in `OnFrameworkInitializationCompleted`, it works. It only doesn't work if I set it in Application's xaml.

**Comment by metal450** [comment]
Workaround: it looks like if I set `Application.Current.RequestedThemeVariant = ThemeVariant.Dark;` programmatically in `OnFrameworkInitializationCompleted`, it works. It only doesn't work if I set it in Application's xaml.

**Comment by amwx** [comment]
Pushed what I think is a fix for this. Didn't test cause it takes forever for an android build to complete, but I think this should work without any side effects. Will be in the 2.0.5 package, if it doesn't work or there are new bugs, let me know.
