### ISSUE TITLE
Can't run on windows7 sp1 due to the use of windows 10 only API.

### ISSUE THREAD

**Issue by sandsc** [amwx/FluentAvalonia#499]
**Describe the bug**
[Win32Interop](https://github.com/amwx/FluentAvalonia/blob/master/src/FluentAvalonia/Interop/Win32Interop.cs) use `AdjustWindowRectExForDpi` which is only available on windows 10. application raise `System.EntryPointNotFoundException` exception when app runs on windows 7.

> Unable to find an entry point named 'AdjustWindowRectExForDpi' in DLL 'user32.dll

**Comment by timunie** [comment]
@sandsc Windows 7 is not officially supported by MS anymore and we have no devices to test it. Thus it is expected that at some point Avalonia may not work on Win7 anymore. If you are able to provide a fix without breaking any functionality, without any hacks, we may include this but no promise. 

Thank you for your understanding.

**Comment by amwx** [comment]
Please also see the readme or the documentation. It states Win 7 and 8 are not supported by FA.
