### ISSUE TITLE
FAComboBox OnTextInput does not fire 

### ISSUE THREAD

**Issue by avalanchus** [amwx/FluentAvalonia#510]
"FAComboBox.OnTextInput" does not fire when entering text or you need to add a public event "OnTextChanged".
I found the handling of changing the Text property in the source code, where the private "OnTextChanged" method is called. It would be good to add the mentioned event.

**Comment by amwx** [comment]
The `TextInput` event comes from higher up in Avalonia itself as a part of `InputElement`. It serves a different purpose and I can't invoke that event anyway since its declared higher up in the hierarchy.
