### ISSUE TITLE
AppWindow - How to add a button on the Titlebar

### ISSUE THREAD

**Issue by Coloris** [amwx/FluentAvalonia#514]
**Describe the bug**

No bug here, just seeking assistance with AppWindow.

I'm wondering if there's a method to add a button (to switch between light and dark modes), similar to what Visual Studio provides. Checked the sample app but can't figure out how the AutoCompleteBox was added there.

**Screenshots**
![](https://github.com/Coloris/FluentAvaloniaNavViewTooltipIssue/blob/main/appwindow.png?raw=true)

**Desktop/Platform (please complete the following information):**
 - OS: Win11
 - FluentAvalonia Version : 2.0.5
 - Avalonia Version : 11.0.6

**Comment by timunie** [comment]
@Coloris why do you open a question as bug report? That's not really fair tbh. Use Discussions for questions pls. 

I think this is the magic code: https://github.com/amwx/FluentAvalonia/blob/30b4379a9c6a7fb2dde62442932e6bc985a23058/samples/FAControlsGallery/Views/MainWindow.axaml.cs#L23-L28

**Comment by Coloris** [comment]
Sorry, you can be sure that if I was aware that such tab existed i would have posted there !

**Comment by timunie** [comment]
All fine 👍
