### ISSUE TITLE
Roll-Up of Changes

### ISSUE THREAD

**Issue by robloo** [amwx/FluentAvalonia#517]
**Is your feature request related to a problem? Please describe.**

This is a roll-up of various issues and upstream changes I've been watching that FluentAvalonia likely needs to address in the future. I'm planning to address each of these later on myself (likely in a few months). However, I expect for some like `BackgroundSizing` others will beat me to it.

 - [x] Port over upstream ColorPicker changes
     * Closed by PR #553
   - [x] Support `Content` property in `ColorPicker` control themes
      * https://github.com/AvaloniaUI/Avalonia/pull/13073
   - [x] `IsDeferredScrollingEnabled` binding in control themes
      * https://github.com/AvaloniaUI/Avalonia/pull/13644
   - [x] Better Flyout positioning in control themes
      * https://github.com/AvaloniaUI/Avalonia/commit/4007dfa0b9ce8d374e58551a0494e2bc29d6ecb3
 - [x] Port over the upstream fix for Expander open/close canceling animations
   * https://github.com/AvaloniaUI/Avalonia/pull/13780 
   * Closed by PR #553
 - [x] Add support for upstream `BackgroundSizing` and remove FluentAvalonia-specific code for this
   * https://github.com/AvaloniaUI/Avalonia/pull/14048 
   * https://github.com/amwx/FluentAvalonia/issues/262
   * Closed by PR #541
 - [x] `HyperlinkButton` is planned to be added upstream. When that happens it can be removed here as well except for the control theme. Even if `HyperlinkButton` doesn't make it in upstream, we should use the new Launcher service coming in.
   * https://github.com/AvaloniaUI/Avalonia/pull/14320
   * https://github.com/AvaloniaUI/Avalonia/pull/14509
   * Closed by PR #541
 - [x] ~DatePicker and TimePicker do not support resizing very well (an issue inherited from upstream WinUI). This needs to be improved as much as possible especially in the horizontal direction. Text trimming can be used, MinWidths removed where possible, etc.~
   * Can't really be changed as the fixed sizes are used several places including the flyout/popup sizing. It's a quite involved change at this point so not going to attempt it for now if at all.

**Describe the solution you'd like**

Described above

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by amwx** [comment]
I'll take care of the BackgroundSizing related stuff later once a release package is available for it, as well as whatever will be done with HyperlinkButton - as I can put the launcher API into the SampleApp so maybe links will work for things other than linux, finally...

**Comment by robloo** [comment]
@amwx `BackgroundSizing`, `HyperlinkButton` and `ILauncher` is all merged in upstream. These should be released with 11.1 timing unknown. But if you want to update to latest nightly it's there.
