### ISSUE TITLE
DataGrid Headers do not Display

### ISSUE THREAD

**Issue by Adaj22** [amwx/FluentAvalonia#519]
**Describe the bug**
When using the Avalonia datagrid control the headers for the columns of the datagrid are not displayed.  This occurs when using either AutoGenerateColumns=true or when specifying the columns headers and bindings.

**Screenshots**
![Missing headers](https://github.com/amwx/FluentAvalonia/assets/119899449/41872e40-82e0-4540-939c-329e5f0dbc23)

**Desktop/Platform (please complete the following information):**
OS: Windows 11 Build 10.0.22631 and Linux Mint 21.3 Virginia 6.5.0-15-generic x86_64
FluentAvalonia Version 2.05
Avalonia Version 11.0.7

**Additional context**
If the FluentAvaloniaTheme is removed from the Application Styles and replaced with the FluentTheme the headers appear as expected.

**Comment by timunie** [comment]
you have make sure the StyleInclude is done correctly? If so, please upload a minimum sample

**Comment by Adaj22** [comment]
Thanks for taking the time to look at this.  A sample VS2022 project is attached.
[DataGrid.zip](https://github.com/amwx/FluentAvalonia/files/14158420/DataGrid.zip)

**Comment by Adaj22** [comment]
I found the issue.  I had included styling for the datagrid.  Sorry to waste your time.

**Comment by timunie** [comment]
@Adaj22 you're welcome. However, please close the issue if it is working for you now. Thx.
