### ISSUE TITLE
Add support for TreeDataGrid control

### ISSUE THREAD

**Issue by ClassyCircuit** [amwx/FluentAvalonia#520]
Could you please add support for TreeDataGrid control? 
https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid

The standard TreeView suffers from serious performance issues when dealing with large trees since it doesn't support virtualization. TreeDataGrid has solved all those issues, so our application is using this control.

I'd be very grateful, if you could add styling to this control.

If there is nobody willing to work on it, I would at least appreciate some pointers in the right direction on how to start styling this control. I have no clue on where to start.

Thanks!

**Comment by amwx** [comment]
See https://github.com/amwx/FluentAvalonia/issues/258
