### ISSUE TITLE
Expander flickers

### ISSUE THREAD

**Issue by styris-ame** [amwx/FluentAvalonia#522]
**Describe the bug**
The expander content flickers after fading in. It's most noticable on the first open in this video, though note that it's not the first time I loaded opened, just luck:

https://github.com/amwx/FluentAvalonia/assets/123859041/5a79e651-bebd-4a5b-b19f-a324379c80ee

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Latest (cloned)
 - Avalonia Version Latest (cloned)

**Comment by robloo** [comment]
This is an upstream issue:
 * https://github.com/AvaloniaUI/Avalonia/issues/13557

It probably should be closed here and tracked in Avalonia itself.

**Comment by styris-ame** [comment]
👍
