### ISSUE TITLE
Option for blue TaskDialogButton color

### ISSUE THREAD

**Issue by styris-ame** [amwx/FluentAvalonia#524]
**Is your feature request related to a problem? Please describe.**
Windows apps usually have a blue dialog button indicating that it is the primary button:

![Screenshot 2024-02-05 151812](https://github.com/amwx/FluentAvalonia/assets/123859041/4dec0208-7a64-42fe-9a34-0e8957df3929)

**Describe the solution you'd like**
An option for a blue button.

**Comment by timunie** [comment]
ContentDialog has it via DefaultButton. I'm not sure about TaskDialog though.

**Comment by amwx** [comment]
Use the `IsDefault` property on a TaskDialogButton to do this
