### ISSUE TITLE
TaskDialog Binding

### ISSUE THREAD

**Issue by kitUIN** [amwx/FluentAvalonia#526]
I try to bind the properties of VM to TaskDialog
```xaml
<ui:TaskDialog
            Header="{Binding Greeting, Mode=OneWay}"
            Name="TaskDialog1">
    <ui:TaskDialog.Buttons>
        <ui:TaskDialogButton DialogResult="OK" Text="OK" />
    </ui:TaskDialog.Buttons>
</ui:TaskDialog>
```
When I  launched it 
```CSharp
this.FindControl<TaskDialog>("TaskDialog1").ShowAsync();
```
It can't show my property `Greeting`, But it's normal for me to use other controls

Is there a way to do this xaml binding?

Current Version
FluentAvalonia : 2.0.5
Avalonia : 11.0.9

**Comment by timunie** [comment]
Make sure DataContext is set correctly for TaskDialog. You can use DevTools F12 to check it.

**Comment by kitUIN** [comment]
I do it!
🥰Thanks!
