### ISSUE TITLE
[Improvement] ContentDialog handle Enter-Key

### ISSUE THREAD

**Issue by timunie** [amwx/FluentAvalonia#53]
Hi @amwx 

## What is the current situation?
I have a `ContentDialog` which has a `UserControl` as content. I would like to perform the closing action when the user hits `Enter`, but only if the password box has focus and has any text. This is not so easy at the moment

## What ideas do I have?
- Adding two more `StyledProperties` called `CancelOnEscape [bool]` and `DefaultOnEnter [bool]` and handle these in the `KeyDown` or `KeyUp`-Event
- Add an overload to `Hide()` which accepts a close reason, like `Hide(ContentDialogResult result)` which closes the dialog and returns the given result

Which solution do you like best? I would be happy to provide the needed PR. 

Happy coding 
Tim

**Comment by amwx** [comment]
Option 2 is probably the best solution. It avoids adding properties, but also I think is the most general purpose for any other use cases.
