### ISSUE TITLE
FAComboBox with IsTextSearchEnabled doesn't search through the whole collection but only the visible items

### ISSUE THREAD

**Issue by Kermel** [amwx/FluentAvalonia#530]
**Describe the bug**
When I fill the combobox with lots of items (let's say a list of world states (around 219 items) the IsTextSearchEnabled feature doesn't work correctly - it always offers only results from the part of the list which is currently visible when combobox is open - i.e. the first items from the list; if I open the combobox and scroll down, then the search will only match with items that I have scrolled-to but never the rest of the combo
(i.e. if I scroll all the way down to "Zambia", the search will not position me on Albania if I start typing "Al...")

**Desktop/Platform (please complete the following information):**
 - OS: [Windows 11]
 - FluentAvalonia Version [latest]
 - Avalonia Version [e.g. latest]

(am I missing some configuration maybe?)

**Comment by timunie** [comment]
currently known issue in upstream Avalonia https://github.com/AvaloniaUI/Avalonia/issues/12490

**Comment by Kermel** [comment]
I see... OK let's wait if this gets some fix
