### ISSUE TITLE
Tab selection does not work when moved to a different window

### ISSUE THREAD

**Issue by tejs-code** [amwx/FluentAvalonia#532]
**Describe the bug**
Repro from the sample app
Select 'Launch' from the TabView windowing sample
Drag Tab2 out so it opens in new window
Drag Tab3 out so it opens in new window
Drag Tab3 into Tab2's window.

The UI appears correct, showing Tab3 and Tab2 in the same window, but selecting Tab2 does not bring the content into view.
If you drag Tab2, the content becomes visible.

Debugging shows the OnPointerPressed in avalonia's ListBoxItem.cs returns early because ItemsControl.ItemsControlFromItemContaner believes the tab's parent is still the original listitem.

**Screenshots**
![Tab-Bug](https://github.com/amwx/FluentAvalonia/assets/1758254/12af21fd-043d-4f57-8d72-b82f77615ec1)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version latest
 - Avalonia Version 11.0.9

**Additional context**

**Comment by amwx** [comment]
Can't repro this in the 2.1 branch (preview), so it may have been an issue upstream with ItemsControl and fixed in Avalonia 11.1.
