### ISSUE TITLE
NavigationView Footer Item Bug

### ISSUE THREAD

**Issue by xSeri98** [amwx/FluentAvalonia#543]
So i just followed the code from the example of fluent avalonia NavigationView creation using the code behind of the view, it works just fine but when i set the "PaneDisplayMode" to LeftCompact the footer items disappear and reappear only upon opening the NavigationViewPane

**Screenshots**

--PaneDisplayMode = Left-- 

![image](https://github.com/amwx/FluentAvalonia/assets/102629371/a5d0a505-036b-4c2a-9eb5-01d414c0ec4a)

--PaneDisplayMode = LeftCompact--

![image](https://github.com/amwx/FluentAvalonia/assets/102629371/5c892d5e-a3b3-44b8-8682-5d875e764e9b)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 
 - FluentAvalonia Version  [latest]
 - Avalonia Version [11.0.10]

**Comment by liaiwu** [comment]
I have been troubled by this BUG for a few days.hope it can be resolved soon.
