### ISSUE TITLE
SelectableTextBlock Issues

### ISSUE THREAD

**Issue by xLEGiON** [amwx/FluentAvalonia#550]
**Describe the bug**

There are a few issues when using the `SelectableTextBlock` with the `FluentAvaloniaTheme`:

1. The `ControlTheme` does not set the `SelectionBrush`, so the selection is not visible. The Avalonia themes added this here: https://github.com/AvaloniaUI/Avalonia/commit/9a3ed2e0228c5d12c773de632805bbf6f944df50. The change just needs to be copied across to the `FluentAvaloniaTheme`.

2. The "Copy" button on the `ContextFlyout` is always visible. The Avalonia themes disable this button when there is no text selected. The expected behavior is that this button would be hidden on the `FluentAvaloniaTheme` when no text is selected.

3. Clicking the "Copy" button on the `ContextFlyout` copies the entire text instead of only the selected text. The expected behavior is that this only copies the selected text.

**Desktop/Platform:**

 - OS: Windows 10
 - FluentAvalonia Version 2.0.5
 - Avalonia Version 11.0.10

**Additional context**

I have tested fixes for these issues and will submit a pull request for consideration.

**Comment by amwx** [comment]
Closed by #551
