### ISSUE TITLE
MacOS titlebar has a space ontop of content window

### ISSUE THREAD

**Issue by programClown** [amwx/FluentAvalonia#559]
Hi amwx,
 
    Why MacOS use AppWindow to self-define titlerbar, a space show ontop of content window?
![775bab9930cf55655a9dd8e1f0b8580](https://github.com/amwx/FluentAvalonia/assets/8369309/441192fc-98e9-4046-96c9-d42c7daa4963)

**Comment by timunie** [comment]
@programClown use DevTools [F12] to investigate visual an logical tree

**Comment by programClown** [comment]
I have checked it, but `FA`'s origin design contains the space. ^_^

**Comment by timunie** [comment]
https://github.com/amwx/FluentAvalonia/blob/d39b8ed848a22109f69e259e304143efdb12e57b/src/FluentAvalonia/Styling/ControlThemes/FAControls/AppWindowStyles.axaml#L141 

should be settable here from code behind, check Demo App for docs and usage

**Comment by programClown** [comment]
@timunie Ok, thanks
