### ISSUE TITLE
Provide ProgressRing and RadialProgressBar control

### ISSUE THREAD

**Issue by DmitryBorodiy** [amwx/FluentAvalonia#561]
ProgressRing is a control that visually indicates progress of an operation with one of two styles: a ring that repeatedly animates, or a ring that fills based on a value. 

The ProgressRing and RadialProgressBar controls must be implemented in FluentAvalonia.

**Comment by timunie** [comment]
There is one in the preview package or have I dreamed that?

**Comment by timunie** [comment]
https://github.com/amwx/FluentAvalonia/pull/558

**Comment by DmitryBorodiy** [comment]
How I can get it?

**Comment by timunie** [comment]
installing preview package or wait for the release or use source directly
