### ISSUE TITLE
NumberBox crashes if there is a bindings to the ViewModel

### ISSUE THREAD

**Issue by DkmS1953** [amwx/FluentAvalonia#566]
**Describe the bug**
A clear and concise description of what the bug is and any steps to reproduce it. Sample code or a minimal repro is helpful.
1. Create the Avalonia MVVM project
2. Place NumberBox control in the main window
3. Create TestNumberBox property in the model
4. Bind 2 and 3 with Value="{Binding TestNumberBox}".
5. Run the program, click on the number in the field, see the NumberBox tools.
6. Click on ✖
7. The program crashes (if it is run under the debugger, it will show an exception in the Main method).
**Screenshots**
![image](https://github.com/amwx/FluentAvalonia/assets/25905429/5d7b2fa5-8e90-49bb-aff6-be1a0284e962)
![image](https://github.com/amwx/FluentAvalonia/assets/25905429/114ec607-591c-4b7f-9926-54b15d74f3e6)

**Desktop/Platform (please complete the following information):**
 - OS: [ Windows (10)]
 - FluentAvalonia Version [latest]
 - Avalonia Version [latest]

**Additional context**
Controls without bindings react normally - after clearing they show the placeholder text.

There is a test project in the attachment.
[NumberBox.MvvM.zip](https://github.com/amwx/FluentAvalonia/files/15273549/NumberBox.MvvM.zip)

**Comment by amwx** [comment]
Your ViewModel property type needs to match the type of `Value` from NumberBox, which is `double`. The binding system won't do that conversion for you.

**Comment by DkmS1953** [comment]
Is this supposed to be a joke? All right.

**Comment by timunie** [comment]
If you clear it, it makes your value null. If your property isn't nullable, that throws if you have compiled bindings enabled. ReflectionBinding can handle it. This is by design.
