### ISSUE TITLE
NullReferenceException is thrown when using FACombBox with Flyout

### ISSUE THREAD

**Issue by kellychen815** [amwx/FluentAvalonia#582]
**Describe the bug**
I am using FAComboBox with Flyout
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/8e714b6e-ea8b-4d78-b629-266510853eb0)
After I set focus to the ComboBox, 
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/237460a4-3da7-4734-b1a5-574f69514112)
and then I clicked somewhere outside the flyout, I immediately got the following exception:
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/6599f91b-68bc-4a51-ab46-fc8a18a3e61e)
From Output, I saw:
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/727bfb82-305d-43d8-a315-116ffe5b374f)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 2.0.5
 - Avalonia Version 11.0.10

**Comment by timunie** [comment]
please file a minimal sample to reproduce.

**Comment by kellychen815** [comment]
> please file a minimal sample to reproduce.

Repro steps:
1. Create an empty Avalonia cross-platform project
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/61208688-6cc0-4322-aa11-35798bf975b8)
2. Install FluentAvalonia and add style in App.axaml
3. Copy below code to MainView.axaml

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:FAComboTests.ViewModels"
             xmlns:ui="using:FluentAvalonia.UI.Controls"
             xmlns:sty="using:FluentAvalonia.Styling"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="FAComboTests.Views.MainView"
             x:DataType="vm:MainViewModel">
  <Design.DataContext>
    <!-- This only sets the DataContext for the previewer in an IDE,
         to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
    <vm:MainViewModel />
  </Design.DataContext>

  <Button Content="Test" HorizontalAlignment="Center" >
    <Button.Flyout>
      <Flyout>
        <StackPanel Margin="24" Orientation="Vertical" Width="280">
          <ui:FAComboBox HorizontalAlignment="Stretch" IsEditable="True" PlaceholderText="Select or insert" />
        </StackPanel>
      </Flyout>
    </Button.Flyout>
  </Button>
</UserControl>
```

4. Build and run
5. Click button to show flyout, and combobox shall be focused automatically
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/59a83b65-1cc2-4f8d-a592-6d88d89d7c75)
**6. Click outside the flyout and you shall be able to see the exception**
![image](https://github.com/amwx/FluentAvalonia/assets/44885867/732c70c8-ea1e-4a50-a8eb-1c8449e87eb9)
