### ISSUE TITLE
TextBox flyout commands and SelectableTextBox command buttons not working

### ISSUE THREAD

**Issue by cricketthomas** [amwx/FluentAvalonia#590]
**Describe the bug**

Command Flyout command buttons are not working with FA added. Nor is the SelectableTextBlock. They key bindings work as expected, its just they don't seem to work when you use the buttons on the flyouts. 

**It works fine in the sample app from the master branch, not sure if this is a bug or if i am just initializing something wrong.** 

Video of it not working:

https://github.com/amwx/FluentAvalonia/assets/15821271/35816b29-6d7e-4c7e-92ca-85d580cf8b32

Video of it working without FA installed:

https://github.com/amwx/FluentAvalonia/assets/15821271/858eec97-92f0-4b8e-94d9-77faf1294a54

**Desktop/Platform:**
 - OS: Windows 11
 - FluentAvalonia Version 2.1.0-preview6 (older previews as well)
 - Avalonia Version 11.1.0-rc1

Reproduction:
This is just a empty .NET 8 application with the latest previews install of Avalonia and FluentAvalonia.

https://github.com/cricketthomas/AvaloniaApplication2

**Comment by xLEGiON** [comment]
As mentioned in https://github.com/AvaloniaUI/Avalonia/issues/16854, PR https://github.com/AvaloniaUI/Avalonia/pull/15466 sets `Target` to `null` at the end of `HideCore(bool canCancel = true)` in PopupFlyoutBase.cs.

FluentAvalonia's CommandBarFlyout.cs calls `HideCore(false)` inside `OnCommandBarButtonInSecondaryCommandsClick(object sender, RoutedEventArgs e)`, which occurs whenever one of the buttons is clicked. I think the `Click` event must be firing before the command method (e.g. `ExecuteCutCommand()` in TextCommandBarFlyout.cs) executes. So the command method reads `Target` as `null` and doesn't do anything.

I tried commenting out `HideCore(false)` to test this and it made the button commands work again but left visual artifacts as it no longer gets properly hidden. I'm not familiar enough with this code to suggest the best way to fix it.

**Comment by amwx** [comment]
This should now be fixed in `master`. To work around the issue, `TextCommandBarFlyout` now holds a `WeakReference` to the `Target` control when it opens so it still has access to that when it closes. I may look back at the WinUI source in the future to see if there's a better fix, but this will do for now.
