### ISSUE TITLE
CoreWindow has no top-border

### ISSUE THREAD

**Issue by RobertBeekman** [amwx/FluentAvalonia#61]
Hello,

I've been enjoying the new update but I noticed the CoreWindow is missing its top-border on Windows 10
![image](https://user-images.githubusercontent.com/8858506/146594926-e8ea1262-4397-4146-9804-f2545d26f4dd.png)

**Comment by amwx** [comment]
On Windows 10 the top border needs to be faked. There's something wrong with windows in Win 10 with the `WS_NOREDIRECTIONBITMAP` extended window style that's needed for WinUI comp (which is enabled by default in the sample app) that causes the top border to disappear with extended frames. 

In moving the code I must've inadvertently deleted the check for windows 10 - as I know this was working before. I'll be sure to add that back, in the meantime adding `Pseudoclasses.Add(":windows10")` to the window ctor should make it work again.

**Comment by RobertBeekman** [comment]
Hey, thanks for the explanation :)
I can confirm the workaround works for now.
