### ISSUE TITLE
ToolTip doesn't work on controls that extended into the titlebar

### ISSUE THREAD

**Issue by Omsad** [amwx/FluentAvalonia#613]
**Describe the bug**
A tooltip will not show on a control that is in the blue area of title bar.

For example the titlebar has been set as:
````c#
    protected override void OnInitialized()
    {
        base.OnInitialized();

        TitleBar.ExtendsContentIntoTitleBar = true;
        TitleBar.Height = 40;
    }
````

![image](https://github.com/user-attachments/assets/6e16329f-493a-49c7-9148-04af81d85dc3)
The blue area has a height of is 39 pixels.
The red area has a height of 40 pixels and is it's parent.
The green area shows a tooltip as expected and is outside the titlebar.

````axml
<DockPanel>
  <Border DockPanel.Dock="Top"
          Background="Red"
          Height="40"
          ToolTip.Tip="This works">
    <Panel>
      <Border Background="Blue"
              Height="39"
              ToolTip.Tip="This doesn't work?">
        <TextBlock Margin="12"
                   Text="Title Bar" />
      </Border>
      <TextBlock Margin="12"
                 Text="Title Bar" />
    </Panel>
  </Border>
  <Border Background="Green"
          ToolTip.Tip="This works">
    <TextBlock
      Margin="12"
      Text="Content" />
  </Border>
</DockPanel>
````

**Desktop/Platform:**
 - OS: Windows 10)
 - FluentAvalonia Version 2.1.0
 - Avalonia Version 11.1.3

**Additional context**
Example project showing the issue. [NoToolTip.zip](https://github.com/user-attachments/files/17243043/NoToolTip.zip)

**Comment by amwx** [comment]
From the documentation found within the sample app:
![image](https://github.com/user-attachments/assets/1ed394c9-88f1-430e-b07a-d4f08a91fe8c)

![image](https://github.com/user-attachments/assets/7500d566-a2c9-40ae-b9b9-1803cefcf867)
