### ISSUE TITLE
The "Export" IconSource Enum value is missing

### ISSUE THREAD

**Issue by dcooperch** [amwx/FluentAvalonia#618]
The "Export" IconSource cannot be resolved because it is missing in 
`Symbol.cs` But is included in `FASymbolFontList.json` Here: 

``` 
 {
    "Name": "Export",
    "Codepoint": "EDE1"
 },
```

Workaround:
```
<CommandBarButton>
  <CommandBarButton.IconSource>
      <FontIconSource Glyph="&#xEDE1;" 
                         FontFamily="{StaticResource SymbolThemeFontFamily}"/>
  </CommandBarButton.IconSource>
</CommandBarButton>
```

**Comment by amwx** [comment]
Please note that the `Symbol` enum is not meant to include all of the icons available in the font file. It was designed to mirror UWP's Symbol enum with a few extras - based on availablility in the FluentUI Icons font. `Export` is not in UWP's Symbol enum and thus wasn't included. As you already know, it is still accessible with a FontIcon/FontIconSource.
