### ISSUE TITLE
[Bug] CommandBar commands out of order

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#62]
I have a CommandBar designed as follows:
```xml
<ui:CommandBar HorizontalAlignment="Stretch" VerticalAlignment="Top" Margin="0,40,0,0" DefaultLabelPosition="Right">
	<ui:CommandBar.Content>
		<TextBlock Margin="6,12,6,0" Text="{Binding Status}"/>
	</ui:CommandBar.Content>
	
	<ui:CommandBar.PrimaryCommands>
		<ui:CommandBarSeparator />

		<ui:CommandBarButton Label="Select Save Folder" Icon="OpenLocal"/>

		<ui:CommandBarButton Label="Download Video" Icon="Download"/>

		<ui:CommandBarSeparator />

		<ui:CommandBarButton Label="Back" Icon="Back"/>

		<ui:CommandBarButton Label="Forward" Icon="Forward"/>

		<ui:CommandBarButton Label="Refresh" Icon="Refresh"/>

		<ui:CommandBarButton Label="Home" Icon="Home"/>

		<ui:CommandBarSeparator />

		<ui:CommandBarButton Label="Settings" Icon="Settings" Command="{Binding SettingsCommand}"/>
	</ui:CommandBar.PrimaryCommands>
</ui:CommandBar>
```

When the application is running, the CommandBar looks normal:
![Good](https://user-images.githubusercontent.com/17648453/146612287-ca7303e5-2eab-44fd-bda2-795214566b3d.png)

However, if the window is resized smaller and the command overflow to the secondary commands menu, the commands then become out of order as so:
![Bad](https://user-images.githubusercontent.com/17648453/146612363-8b086a6f-0d85-4dd7-b2f3-a20c70777eee.png)

**Comment by amwx** [comment]
When overflowing, the commands are moved from primary to secondary from right to left (unless dynamic overflow order is specified) and inserted to the top of the list. A separator is added at the end of overflow to separate overflow from permanent secondary items. Any separators within the primary list are collapsed and not moved to overflow - which is the correct UWP behavior. 

So in your case, the separator you added between home and settings is collapsed, and the one you're seeing in the overflow dropdown is the one added to separate overflow from secondary. What I probably need to fix here is not showing that separator if there's no permanent secondary items.
