### ISSUE TITLE
Add Snackbar Control with Auto-hide, Message Queuing, and Animations

### ISSUE THREAD

**Issue by lebhero** [amwx/FluentAvalonia#621]
**Is your feature request related to a problem? Please describe.**

Sometimes it's important to show a temporary message to the user that will automatically disappear after a set duration. For instance, I have a small application that updates the database in the background, and I need to show a brief notification (around 5 seconds) informing the user about the completed action. Currently, the user can click on an action button labeled "Details" to open a new view with the full update details. While the Infobar control exists, it doesn't fully meet my needs. Specifically, it lacks the ability to auto-hide after a specified time, and it isn't as visually dynamic or flexible for this use case.

**Describe the solution you'd like**

- Auto-close functionality: The snackbar should disappear automatically after a specified time (e.g., 5 seconds). If not time is set then it will just stay open until the user close it manually.
- Message queuing: It should support queuing multiple messages, displaying them one after the other.
- Slide-in/Slide-out animations: The snackbar should have smooth animations when it appears and disappears (e.g., sliding from the bottom).
- Customizable message content: The control should allow for custom content, including text and optional action buttons (e.g., "Undo" or "Details").
- Message prioritization: The ability to prioritize certain messages in the queue or display an important message immediately if needed.
- Styling options: The snackbar should allow for custom styling and theming, enabling the user to adjust colors, padding, and other visual aspects (Optional).

**Describe alternatives you've considered**

I have considered using the Infobar, but it lacks several key features, such as auto-hide timing, smooth animations, and message queuing. As such, it doesn't fulfill the requirements for this particular use case.

**Additional context**

A snackbar would be a highly useful addition to the FluentAvalonia toolkit, as it would provide a more visually engaging and dynamic way to display brief, non-intrusive notifications in applications. If possible, a demo or example implementation would be great to help with integration.

**Comment by timunie** [comment]
Isn't WindowNotificationManager what you need? It's a plain Avalonia control. Check Avalonia sample for reference. https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Notifications/WindowNotificationManager.cs

**Comment by amwx** [comment]
As Tim said above, Avalonia's built-in `WindowNotificationManager` already exists. If that isn't feature complete enough for you, either make feature requests upstream or make a new proposal that explains how a new control could *significantly* fill the gap that doesn't exist.
