### ISSUE TITLE
FluentAvalonia does not compile with avalonia 11.2

### ISSUE THREAD

**Issue by joer33304** [amwx/FluentAvalonia#623]
When upgrading to avalonia 11.2, the FluentAvalonia project does not compile.
It shows various missing items in the DateTimePicker style file

**Comment by fredericoregateiro** [comment]
I'm also having a problem with the `TimePicker` the code compiles but the designer stops working.

the output shows an error but not much information
```
19:13:02.441 [Debug] 29776 <= UpdateXamlResultMessage { Error: "System.NullReferenceException: …", Handle: null, Exception: ExceptionDetails { ExceptionType: "NullReferenceException", Message: "Object reference not set to an …", LineNumber: null, LinePosition: null } }
19:13:02.441 [Error] 29776 UpdateXamlResult error
System.Xaml.XamlException: Object reference not set to an instance of an object.
19:13:02.446 [Verbose] 29776 Finished PreviewerProcess.OnMessageAsync()
```

**Comment by beginor** [comment]
Confirm same issue with AbaloniaUI 11.2

https://github.com/AvaloniaUI/Avalonia/issues/17419

**Comment by Philltorian** [comment]
A fix for this has just been committed into Avalonia

[Fix TimePicker breaking change, when using pre-11.2 styles #17516](https://github.com/AvaloniaUI/Avalonia/pull/17516)

**Comment by amwx** [comment]
Closing, as this is result of Avalonia breaking change in a minor version + should also be fixed now.
