### ISSUE TITLE
 Remove the TitleBar from AppWindow.

### ISSUE THREAD

**Issue by Lv-jinyuan** [amwx/FluentAvalonia#625]
**Describe the bug**
In the AppWindow, ExtendClientAreaChromeHints and ExtendClientAreaTitleBarHeightHint are not effective.

It is caused by EnsureExtended in FluentAvalonia/src/FluentAvalonia/UI/Windowing/Win32/Win32WindowManager.cs.

**Comment by amwx** [comment]
Please do not use those properties when using `AppWindow`. If you want further customization on the look of your window, AppWindow is not for you, stick with normal Window and use those properties to get the look you want.
