### ISSUE TITLE
Search for font instead of based off of OS

### ISSUE THREAD

**Issue by BrycensRanch** [amwx/FluentAvalonia#627]
**Is your feature request related to a problem? Please describe.**
FluentAvalonia should be looking for the presence of Segoe UI instead of basing it off of OS type. There's nothing to stop a Linux user from downloading and installing the font. For example:

![image](https://github.com/user-attachments/assets/4c49f1dd-44fd-4095-b89f-9b740101c3a9)

![image](https://github.com/user-attachments/assets/068189a0-56d2-4d75-a710-0aa77a2d29f5)

**Describe the solution you'd like**
Refactor checks to check for the font, not the OS

**Describe alternatives you've considered**
Yes

**Additional context**
N/A

**Comment by amwx** [comment]
This is best left up to individual applications. Loading and searching the system font collection is slow and I'm not burdening all users of FA at app startup just to catch the rare chance that someone not on Windows has Segoe UI/Segoe UI Variable installed.

**Comment by BrycensRanch** [comment]
It was worth a try. 😔
