### ISSUE TITLE
More than just Primary, Secondary and Close  button!

### ISSUE THREAD

**Issue by aboimpinto** [amwx/FluentAvalonia#64]
Hello, 

It's possible to have more buttons than Primary, Secondary or Close?

Can I have a button with a custom command? An example is to have several buttons on the Dialog that will change what is happening in the dialog.

I thought that I could use a Custom UserControl with as many buttons as I want, but, I have to define the button any way.

Is this possible?

best regards
Paulo Aboim Pinto

**Comment by amwx** [comment]
> It's possible to have more buttons than Primary, Secondary or Close?

No, there are only 3 built in buttons for the `ContentDialog`, however (see below)

> Can I have a button with a custom command? An example is to have several buttons on the Dialog that will change what is happening in the dialog.

Yes each of the built in buttons has a Command and CommandParamater property that you can bind to to execute a custom command

> I thought that I could use a Custom UserControl with as many buttons as I want, but, I have to define the button any way.
> 
> Is this possible?

`ContentDialog` is a `ContentControl`, so while there's a limited number of built in action buttons, you can put any kind of content inside of it and have the dialog do whatever you want.

**Comment by aboimpinto** [comment]
thanks!!!

**Comment by emmauss** [comment]
Could you provide or expose  styles to control the width of the title bar buttons in CoreWindow? It appears too wide on my window, but looks normal on the samples.
Also, it seems icons are not supported yet for CoreWindow

**Comment by aboimpinto** [comment]
On the Showcase Application that I'm building for Avalonia, I decide to create my own DialogModal control and here is the Story for it:
https://github.com/aboimpinto/Avalonia.SalesApp/issues/7

I'm using the FluentAvalonia as a template, because uses most of the features that I require, but, not the flexibility of customizing.
I hope that we can work together and in the end, we can have better DialogModal control that can be used by anyone.

What do you think? Do you have any requirements that would like to see implemented too?

**Comment by amwx** [comment]
> Could you provide or expose styles to control the width of the title bar buttons in CoreWindow? It appears too wide on my window, but looks normal on the samples. Also, it seems icons are not supported yet for CoreWindow

Please create a separate issue as these are unrelated to this issue. However, caption button size issue may be a DPI thing? Are you using a high dpi display? A screenshot would be helpful too. 
As for icons, they won't be built in to the `CoreWindow` class - icons really aren't in the modern window style, which CW mimics. You should, however, be able to supply a custom titlebar with an `Image` control and get an icon that way. This is what modern apps like the Microsoft store or Calculator do. I haven't test this, but it should still be possible to bind this to the `Icon` window property to get the same icon as the one displayed in the taskbar. I'm planning to re-do the Sample App next month and I'll include some examples of customizing the `CoreWindow` class, and make sure this all works.

**Comment by amwx** [comment]
> On the Showcase Application that I'm building for Avalonia, I decide to create my own DialogModal control and here is the Story for it: [aboimpinto/Avalonia.SalesApp#7](https://github.com/aboimpinto/Avalonia.SalesApp/issues/7)
> 
> I'm using the FluentAvalonia as a template, because uses most of the features that I require, but, not the flexibility of customizing. I hope that we can work together and in the end, we can have better DialogModal control that can be used by anyone.
> 
> What do you think? Do you have any requirements that would like to see implemented too?

What customizations are you specifically looking for? `ContentDialog` here is modeled after the one in UWP/WinUI, it's goal is just a simple message box used to prompt the user. Granted, others try to extend it way beyond this, but that is its core purpose. As such, things you're looking for are unlikely to make it into the core ContentDialog class, however, you can take what I've done and adapt it for your needs, which it looks like you're already doing. Whether or not you can just inherit from `ContentDialog` or if you need to start from scratch I don't know, again that really depends on what specific things you're trying to implement.
