### ISSUE TITLE
DataGrid ContextMenu broken

### ISSUE THREAD

**Issue by fmaeseele** [amwx/FluentAvalonia#66]
Hi,

I'm having a simple DataGrid with a ContextMenu for rows, but using FluentAvalonia is breaking the displaying of the ContextMenu. It doesn't display anymore.

`<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:AvaloniaApplication2"
             xmlns:sty="using:FluentAvalonia.Styling"
             x:Class="AvaloniaApplication2.App">
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    <Application.Styles>
      
      

      
      <sty:FluentAvaloniaTheme/>
    </Application.Styles>
</Application>
`

If I want the ContextMenu to be displayed with a right click, I have to uncomment the Avalonia Styles in the App.axaml, but it requires to select a theme which is done automatically by FluentAvalonia. Then, if I let the both declarations, it breaks other visual aspects (Expander header foreground for example).
I have no idea what could prevent the ContextMenu to be displayed looking at the DataGrid styles definitions.

Thanks for your help.
I have attached the project sample.
[AvaloniaApplication2.zip](https://github.com/amwx/FluentAvalonia/files/7795082/AvaloniaApplication2.zip)

**Comment by amwx** [comment]
Use `ContextFlyout` instead, it's a newer, more flexible API but works exactly the same for a simple context menu. I didn't include the styles for `ContextMenu` in FluentAvalonia for the encouragement of moving to flyouts, which is why it's not showing.

Use context flyout like this (ex. attaching to a Panel)
````
<Panel>
    <Panel.ContextFlyout>
        <MenuFlyout>
            <!-- You can either bind items here or specify them in xaml -->
        </MenuFlyout>
    </Panel.ContextFlyout>
</Panel>
````

**Comment by fmaeseele** [comment]
Thank you very much.

For other people interested in this, here how I was setting the ContextMenu on the DataGridRow:

```
        <DataGrid.Styles>
          <Style Selector="DataGridRow">
            <Setter Property="ContextMenu" Value="{DynamicResource ItemContextMenu}" />
          </Style>
        </DataGrid.Styles>
```

And here is how to set the FlyoutMenu instead:
```
        <DataGrid.Styles>
          <Style Selector="DataGridRow">
            <Setter Property="ContextFlyout" Value="{DynamicResource testMenu}" />
          </Style>
        </DataGrid.Styles>
```

Thank you.
Closing the issue.
Have a nice New Year evening!
