### ISSUE TITLE
Navigating through page loose visual tree state

### ISSUE THREAD

**Issue by fmaeseele** [amwx/FluentAvalonia#67]
Hi,

Using a NavigationView, every time  I navigate from page to page, each page loose its visual tree state.
If for example, on page one, you have scrolled down to the page, when you get back to it, the visual state is restored as if it was the first time displayed.
Is there a workaround for that, or is a planned feature ?

Best Regards,
François

**Comment by amwx** [comment]
I can't repro this using the sample app, the scroll state is maintained when navigating away and then back. Are you using a `Frame` control with the `NavigationView`? `Frame` will cache previous pages (up to the cache limit, default = 10) so they can be properly restored. Otherwise I think this is expected behavior. Interestingly in WinUI's xaml controls gallery, I observed both behaviors depending on which page I flipped between.

**Comment by fmaeseele** [comment]
In my case, I was using a CommandBar with CommandBarButtons with Labels. Switching to another view and getting back, my CommandBarButtons were not displaying anymore the labels. After debugging, what happens is simple: when you switch to another view, your page is detached from the visual tree. Here, the CommandBarButtons IsOpen property is set to false. When you get back to your page, there is no code to restore the IsOpen state property. So my CommandBarButtons are only displaying the icons.
I have this issue with your CommandBar control, but I think this is more a general design pattern issue in your library (meaning you need to manage this situation globally). You need to think that using your NavigationView, each of your page need to restore its visual tree state.
Your Frame control doesn't help at all as it caches only the IControl object without the visual tree state. It prevents the view model recreation, but the solution is not complete here.
Also, I have a question: Do I need to use the CommandBarButtons inside a CommandBar control ? If not, I could get rid of this issue easly.
Let me know if I can help more.

Best Regards,
François

**Comment by amwx** [comment]
> In my case, I was using a CommandBar with CommandBarButtons with Labels. Switching to another view and getting back, my CommandBarButtons were not displaying anymore the labels. After debugging, what happens is simple: when you switch to another view, your page is detached from the visual tree. Here, the CommandBarButtons IsOpen property is set to false. When you get back to your page, there is no code to restore the IsOpen state property. So my CommandBarButtons are only displaying the icons. I have this issue with your CommandBar control, but I think this is more a general design pattern issue in your library (meaning you need to manage this situation globally). You need to think that using your NavigationView, each of your page need to restore its visual tree state. Your Frame control doesn't help at all as it caches only the IControl object without the visual tree state. It prevents the view model recreation, but the solution is not complete here. Also, I have a question: Do I need to use the CommandBarButtons inside a CommandBar control ? If not, I could get rid of this issue easly. Let me know if I can help more.
> 
> Best Regards, François


That's expected to happen, and even how it works in UWP/WinUI. `IsOpen` is primarily is tied to the dropdown used for SecondaryCommands, which opens even if you have nothing in the dropdown. Disconnecting from the tree closes the popup, which sets IsOpen to false. So this is more an issue of using the control differently from how Microsoft designed it to be used. That said, the level of state saving you desire here is beyond what I can provide as a general solution in the library, and is better left to individuals to implement if they need it - things can get complex very quickly. For most, the default behavior is what they expect.


>Do I need to use the CommandBarButtons inside a CommandBar control ? If not, I could get rid of this issue easly.
> 

Technically no, but some of the visual states are tied to the `CommandBar` so they will lose some features. But they will still function as a button.
