### ISSUE TITLE
How do I disable the selection indicator in TreeView ?

### ISSUE THREAD

**Issue by geometrikal** [amwx/FluentAvalonia#71]
I'm using TreeView but with check boxes for some data templates so that I can more easily do multiple selection.

However, using the FluentAvalonia style it also adds in a small selection border, how do I disable this with a style?

I tried 
```
<UserControl.Styles>
        <Style Selector="TreeViewItem /template/ Border#SelectionIndicator">
            <Setter Property="Width" Value="0"/>
        </Style>
    </UserControl.Styles>
```

but it didn't change anything

**Comment by amwx** [comment]
You should just be able to target it's visibility instead when the item is selected

````
Selector="TreeViewItem:selected /template/ Border#SelectionIndicator"
   Setter Property=IsVisible Value=False
````

The SelectionIndicator has it's width set inside the template, which means it gets LocalValue priority and then can't be overriden by other styles - a flaw in Avalonia's value priorities within templates. Technically I should move that to a dedicated style so it can be overridden but that clutters template files up and I'm still hoping this gets resolved.

**Comment by geometrikal** [comment]
Thankyou!
