### ISSUE TITLE
Invalid TitleBar colors when switching themes

### ISSUE THREAD

**Issue by fmaeseele** [amwx/FluentAvalonia#73]
Hi,

Starting Sample application with Windows 10 in DarkMode, go to Settings and click on Set LightTheme. The application title become invisible, title bar min/max/close buttons also (unless you move pointer over them).
Same thing if your windows is in LightTheme and you try to change your Sample application theme to Dark.

I have tested this behaviour under Windows 10 (latest version) and Windows 11.
I don't know about Unbuntu nor MacOs.

Note: Whatever your Windows theme configuration, when you start your sample application, the titlebar colors are ok. The issue only happens when you switch to another theme from the Sample application. 

If you could have a look... 
This is not critical, but as I propose to change theme in my application as in your sample application, it would be great that this works correctly.

At the same time, have you noticed that in your sample application, let's say your windows is in Dark mode, you have a slim white border arroud your main window ?

**Comment by amwx** [comment]
They're not invisible, just forced to white text. Added to my list to fix.

> At the same time, have you noticed that in your sample application, let's say your windows is in Dark mode, you have a slim 
white border arroud your main window ?

I haven't noticed that. Is this Win 10 or 11, and do you have a screenshot?

**Comment by fmaeseele** [comment]
![image](https://user-images.githubusercontent.com/4427600/149866736-41f9d380-655c-48bc-9c41-a83ba79c7358.png)

Not sure this is visible with this screenshot....

**Comment by amwx** [comment]
It's hard to tell from that screenshot, but it might be the System window border - which isn't hide-able in `CoreWindow`. Do you have the windows setting "show accent color on window borders and titlebars" turned off? If so, that would explain why it's white as Win32 apps default to light mode. Although, the app theme should be forced to dark mode, so that logic (which does use undocumented Windows APIs) may have broken - I'll need to check that.

**Comment by nlogozzo** [comment]
I had a similar issue with changing themes on my application and I found that calling `ForceNativeTitleBarToTheme` again after every theme change seemed to fix the issue.

**Comment by fmaeseele** [comment]
> I had a similar issue with changing themes on my application and I found that calling `ForceNativeTitleBarToTheme` again after every theme change seemed to fix the issue.

The sample application already does that and have the issue.

**Comment by amwx** [comment]
On Win11, this is what I see. If this is the thin white border you're referring to that's expected - its the normal system window border in dark mode if you have the "show accent color on title bars and windows borders" system setting turned off:

![image](https://user-images.githubusercontent.com/40413319/150612678-5f84ecb3-1a8a-4240-a2f1-0483c64a6442.png)

**Comment by emmauss** [comment]
Here's an example,
![image](https://user-images.githubusercontent.com/5307160/151669784-b6f87a57-57c7-4b17-9ab8-3e7c0c80c41b.png)
![Screenshot (103)](https://user-images.githubusercontent.com/5307160/151669854-e709ba1b-60c9-49c7-aa20-fa1ed1678ac4.png)

I only changed the theme within the app
