### ISSUE TITLE
Touch Input and NavigationView

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#75]
Touch input seems to not work when interacting with a NavigationView. 
Buttons, ComboBoxs, Textboxs all work with touch input (i.e. they select when you touch them), however not with a NavigationView. 
I am able to touch the hamburger menu and it retracts and expands the NavigationView, however touching a NavigationViewItem does not select the item and change the page like it should.

**Comment by amwx** [comment]
Repro'd on my Surface and to fix you need to enable multitouch in platform settings:
````
 public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace()
                .With(new Win32PlatformOptions()
                {
                    UseWindowsUIComposition = true,
                    EnableMultitouch = true
                });
````

**Comment by nlogozzo** [comment]
Ah ok, thanks!

**Comment by fmaeseele** [comment]
> Repro'd on my Surface and to fix you need to enable multitouch in platform settings:
> 
> ```
>  public static AppBuilder BuildAvaloniaApp()
>             => AppBuilder.Configure<App>()
>                 .UsePlatformDetect()
>                 .LogToTrace()
>                 .With(new Win32PlatformOptions()
>                 {
>                     UseWindowsUIComposition = true,
>                     EnableMultitouch = true
>                 });
> ```

According to the documentation and code, the property EnableMultitouch is true by default. This is weird that you have to forcebly set it to true ?

**Comment by amwx** [comment]
Reopening this. Turns out that's not the solution. It seems something regressed between Avalonia 0.10.10 and 0.10.11 that's causing this (I changed the package version but forgot). If I can figure out what regressed, I'll open a bug report on Avalonia's repo.

**Comment by nlogozzo** [comment]
Sounds good, thanks
