### ISSUE TITLE
Can't download FluentAvalonia

### ISSUE THREAD

**Issue by Pietro228** [amwx/FluentAvalonia#78]
**Describe the bug**
Can't download FluentAvalonia to Avalonia. It shows me that I have to downgrade version but it's already downgraded in project solution.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/53868994/150747345-5fd1b3b1-de7f-4cd9-bf04-1f97f293a683.png)
![obrazek](https://user-images.githubusercontent.com/53868994/150747498-824a8d22-c300-4bf5-bb08-301cf4aa2968.png)

**Desktop (please complete the following information):**
 - OS: Window 11
 - FluentAvalonia Version 1.1.8
 - Avalonia Version 0.10.10

**Comment by Apollo199999999** [comment]
You should try upgrading the Avalonia NuGet packages to 0.10.11 from 0.10.10

**Comment by Pietro228** [comment]
It worked :D Thank you for help. I don't know why it was not updated in sample project
