### ISSUE TITLE
Dark theme doesn't work properly

### ISSUE THREAD

**Issue by Pietro228** [amwx/FluentAvalonia#79]
**Describe the bug**
When I set dark theme and click on button it will quickly change colors from white to gray.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/53868994/150751108-3fab2d02-2f29-480a-9341-fbcc4f780826.png)
![obrazek](https://user-images.githubusercontent.com/53868994/150751114-f0646706-b5d2-4c93-8ad2-cda11d631b3b.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - FluentAvalonia Version 1.1.8
 - Avalonia Version 0.10.11

**Comment by Apollo199999999** [comment]
Could you show your App.axaml?

**Comment by Pietro228** [comment]
```
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:sty="using:FluentAvalonia.Styling"
             xmlns:ui="using:FluentAvalonia.UI.Controls"
             xmlns:uip="using:FluentAvalonia.UI.Controls.Primitives"
			 x:Class="AvaloniaApplication.App">
	<Application.Styles>
		<sty:FluentAvaloniaTheme/>
        <FluentTheme Mode="Dark"/>
    </Application.Styles>
</Application>
```

**Comment by Apollo199999999** [comment]
Could you try removing ```<FluentTheme Mode="Dark"/>```?
