### ISSUE TITLE
How do I enable Mica effect?

### ISSUE THREAD

**Issue by Pietro228** [amwx/FluentAvalonia#81]
**Is your feature request related to a problem? Please describe.**
How do I enable Mica effect for my window?

**Describe the solution you'd like**
Enable Mica effect for my window.

**Comment by Apollo199999999** [comment]
Mica isn't included in FluentAvalonia. However, https://github.com/AvaloniaUI/Avalonia/issues/6465 might be useful

**Comment by Pietro228** [comment]
That's a pity. Because that's the last thing stopping me from using Avelonia.
I haven't managed to get it working :/

**Comment by amwx** [comment]
This question would be better suited for the main Avalonia repo, as it doesn't relate to FluentAvalonia directly. However, easy enough answer:

To enable mica effect, you need to do two things:
First, enable WinUIComposition in the AppBuilder (program.cs), this uses a Window that has access to the WinUI compositor as Mica/Acrylic is not supported by Win32:
````
public static AppBuilder BuildAvaloniaApp()
			=> AppBuilder.Configure<App>()
				.UsePlatformDetect()
				.LogToTrace()
				.With(new Win32PlatformOptions
				{
					UseWindowsUIComposition = true
				});
````

And two, set `TransparencyLevelHint` on your window to `Mica`, and then it will work:

![image](https://user-images.githubusercontent.com/40413319/150871623-c67ed2e9-ed5f-43a4-90b9-cbae2d1acbdb.png)
