### ISSUE TITLE
Menu Item Icon shows a white rect on Dark Theme

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#86]
**Describe the bug**
On Dark Theme, if a menu item has an icon, it shows a white rectangle behind the icon

**Screenshots**
https://cdn.discordapp.com/attachments/798873710097727498/939074611683934228/Screencast_from_02-04-2022_082451_AM.webm

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - FluentAvalonia Version: 1.2.0
 - Avalonia Version : 0.10.11

**Additional context**

**Comment by amwx** [comment]
Apologies. That's something left over from diagnosing the menu padding issue that was fixed. Am quick fixing
