### ISSUE TITLE
ColorPicker icons do not display properly

### ISSUE THREAD

**Issue by Apollo199999999** [amwx/FluentAvalonia#89]
**Describe the bug**
The icons in the ColorPicker do not display properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/60572589/152680205-e18f1779-ffd6-477e-b9cb-e5084dcc972b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 1.2.1
 - Avalonia Version 0.10.12

**Comment by robloo** [comment]
The Avalonia font includes the up/down chevrons so I don't think this is a font issue. I guess perhaps the symbol font needs to be specified here though:

https://github.com/amwx/FluentAvalonia/blob/595830eee00f57d7c8222f00fb9629111dc92eb1/FluentAvalonia/Styling/Controls/NumberBoxStyles.axaml#L199-L208

**Comment by amwx** [comment]
The FontFamily is set in the `NumberBoxSpinButtonStyle` style declaration. As soon as I finish fighting with Avalonia's drag-drop system for the TabView port I'm working on I'm gonna look into this because this was working before and broke recently

**Comment by robloo** [comment]
> The FontFamily is set in the NumberBoxSpinButtonStyle style declaration

I see, really strange that doesn't work.

> but I also see some gaps in the transparency checkerboard background.

If it's an issue with SkiaSharp (and the issues have been piling up), I have the code in the UWP community toolkit to just do all the rendering and compositing directly in C# for an entire color channel slider. It avoids these sorts of things and was needed for the Uno Platform (but still ended up being too much for Uno to handle).

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/b39d70f6ea4d739a470768c103c8af2c5b1e02ef/Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPickerRenderingHelpers.cs#L39

**Comment by amwx** [comment]
> If it's an issue with SkiaSharp (and the issues have been piling up), I have the code in the UWP community toolkit to just do all the rendering and compositing directly in C# for an entire color channel slider. It avoids these sorts of things and was needed for the Uno Platform (but still ended up being too much for Uno to handle).
> 
> https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/b39d70f6ea4d739a470768c103c8af2c5b1e02ef/Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPickerRenderingHelpers.cs#L39


I'm pretty sure it's something related to Skiasharp. A similar issue has popped up with the tabview rendering:
![image](https://user-images.githubusercontent.com/40413319/152904481-a147de8c-e2ba-4429-b729-bbce0ca301a6.png)

If I resize the window width, I can make that little gap at the bottom of the tab go away:
![image](https://user-images.githubusercontent.com/40413319/152904517-2a2c5dab-a0d7-4b42-9982-e24d4e5f3cd0.png)

I've double checked and nothing seems out of order so I'm thinking something is messed up with skia. I think I saw the other day someone say skia is on their like 150th preview of v2.88, so it seems there are bugs a plenty right now 😂But I hadn't seen that issue with the color picker sliders until that screenshot so I need to recreate it first, and I'll keep your link in the back of my mind in case.

**Comment by robloo** [comment]
For the TabView see https://github.com/microsoft/microsoft-ui-xaml/pull/6644

**Comment by amwx** [comment]
I figured out what's causing the OP issue. The NumberBox template is redefined in `ColorPickerStyles.axaml`, and I forgot to update the glyph codepoints when the font was switched - so this has been broken for a while. *facepalm*
I think it might be better to just add the `InnerLeftContent` and `InnerRightContent` defined on Avalonia's `TextBox` to the `NumberBox` to avoid needing a completely new template.
