### ISSUE TITLE
OnNavigatedTo

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [amwx/FluentAvalonia#9]
This is more of a question than an issue.

With UWP / WINUI you can send a parameter "ContentFrame.Navigate(Type, parameter)" and receive it through "OnNavigatedto(NavigationEventArgs e)". Have you implemented something similar?

**Comment by amwx** [comment]
Yes, it is implemented: 
https://github.com/amwx/FluentAvalonia/blob/7bd06ed2cafceb19c04ea5329c8cc230961dabee/FluentAvalonia/UI/Controls/Frame/Frame.cs#L167

https://github.com/amwx/FluentAvalonia/blob/7bd06ed2cafceb19c04ea5329c8cc230961dabee/FluentAvalonia/UI/Controls/Frame/Frame.cs#L283-L287

**Comment by kvalitetskontrollMarkaryd** [comment]
Thanks for your reply!

But how do you receive it when there is no "OnNavigatedto(NavigationEventArgs e)" to override, due to no Page in Avalonia?

**Comment by amwx** [comment]
Ahh I see the issue. Probably the best way to get around this limitation would be to handle the `Navigated` event of the `Frame` in code behind. The `Content` property of the `NavigationEventArgs` has the "page", or view, being loaded and you can pass in/handle whatever logic you need there.

**Comment by kvalitetskontrollMarkaryd** [comment]
You wrote that you are working on a major update, nice!
Is this something you are going to work on to? I have not been able to figure out how to do this work-around.

**Comment by amwx** [comment]
No, I have no plans to implement a `Page` for Avalonia.
The workaround is basically implementing it yourself. This is how I would do it (note, untested code)

Assume you want to load 'HomePage'
In HomePage.cs:
````
public class HomePage : UserControl
{
    //Add this method to handle navigation
    public void OnNavigated(NavigationEventArgs args)
    {
        //Add your custom logic here
    }
}
````
In MainWindow.cs:
````
//In constructor for ease
//Get reference to the Frame control
var frame = this.FindControl<Frame>("MyFrame");
frame.Navigated += OnFrameNavigated;

private void OnFrameNavigated(object sender, NavigationEventArgs e)
{
    if (e.SourcePageType == typeof(HomePage))
    {
        (e.Content as HomePage).OnNavigated(e);
    }
}
````

**Comment by kvalitetskontrollMarkaryd** [comment]
This is great, works perfectly! Thanks!

You should include this as a how to or an instruction. Thanks again!
