### ISSUE TITLE
Unable to drag window with custom toolbar

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#90]
**Describe the bug**
Following the guide in the core window sample, I'm not able to drag the window using the title bar. A very simple sample can be found here demonstrating the issue. https://github.com/emmauss/coretest

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 1.2.1
 - Avalonia Version 0.10.11

**Additional context**

**Comment by Apollo199999999** [comment]
In ```MainWindow.axaml``` try removing ```IsHitTestVisible="False"``` from the ```Grid```

**Comment by emmauss** [comment]
Thanks, that worked
