### ISSUE TITLE
ScrollViewer showing scrollbar when not needed

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#99]
![image](https://user-images.githubusercontent.com/17648453/154811379-a327b2ae-536d-4913-b3ec-465ef518143c.png)

Setting `VerticalScrollBarVisibility` to Auto has no effect

**Comment by amwx** [comment]
Looks like whatever you're hosting in the ScrollViewer is measuring too large, dev tools would show this. Can this be repro'd with the default Fluent theme? This feels more like ScrollViewer measurement funny business than theme related - but without knowing more about how you have this setup, I'm not sure

**Comment by nlogozzo** [comment]
I think it's ScrollViewer funny business. On my laptop the scrollbar is always shown (which is scaled 1.25x), however on my desktop the scrollbar is only shown when needed
